name-template: 'Modus Web Components $RESOLVED_VERSION'
tag-template: 'moduswebcomponents-$RESOLVED_VERSION'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'new-feature'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  default: patch
categories:
  - title: '❗ Breaking Changes'
    labels:
      - 'breaking-change'
  - title: '🚀 Features'
    labels:
      - 'new-feature'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📖 Docs'
    labels:
      - 'docs'
      - 'documentation'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
change-template: '- [#$NUMBER]($URL): $TITLE (@$AUTHOR)'
template: |
  ## Changes

  $CHANGES
