'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type IAutocompleteItem, type IBreadcrumb, type IPageChange, type IRatingChange, type IThemeConfig, type ModusWcAutocompleteCustomEvent, type ModusWcBreadcrumbsCustomEvent, type ModusWcButtonCustomEvent, type ModusWcCheckboxCustomEvent, type ModusWcChipCustomEvent, type ModusWcDateCustomEvent, type ModusWcNavbarCustomEvent, type ModusWcNumberInputCustomEvent, type ModusWcPaginationCustomEvent, type ModusWcRadioCustomEvent, type ModusWcRatingCustomEvent, type ModusWcSelectCustomEvent, type ModusWcSliderCustomEvent, type ModusWcTableCustomEvent, type ModusWcTextInputCustomEvent, type ModusWcTextareaCustomEvent, type ModusWcThemeSwitcherCustomEvent, type ModusWcTimeInputCustomEvent, type ModusWcToggleCustomEvent } from "@trimble-oss/moduswebcomponents";
import { ModusWcAccordion as ModusWcAccordionElement, defineCustomElement as defineModusWcAccordion } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-accordion.js";
import { ModusWcAlert as ModusWcAlertElement, defineCustomElement as defineModusWcAlert } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-alert.js";
import { ModusWcAutocomplete as ModusWcAutocompleteElement, defineCustomElement as defineModusWcAutocomplete } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-autocomplete.js";
import { ModusWcAvatar as ModusWcAvatarElement, defineCustomElement as defineModusWcAvatar } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-avatar.js";
import { ModusWcBadge as ModusWcBadgeElement, defineCustomElement as defineModusWcBadge } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-badge.js";
import { ModusWcBreadcrumbs as ModusWcBreadcrumbsElement, defineCustomElement as defineModusWcBreadcrumbs } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-breadcrumbs.js";
import { ModusWcButton as ModusWcButtonElement, defineCustomElement as defineModusWcButton } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-button.js";
import { ModusWcCard as ModusWcCardElement, defineCustomElement as defineModusWcCard } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-card.js";
import { ModusWcCheckbox as ModusWcCheckboxElement, defineCustomElement as defineModusWcCheckbox } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-checkbox.js";
import { ModusWcChip as ModusWcChipElement, defineCustomElement as defineModusWcChip } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-chip.js";
import { ModusWcCollapse as ModusWcCollapseElement, defineCustomElement as defineModusWcCollapse } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-collapse.js";
import { ModusWcDate as ModusWcDateElement, defineCustomElement as defineModusWcDate } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-date.js";
import { ModusWcDivider as ModusWcDividerElement, defineCustomElement as defineModusWcDivider } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-divider.js";
import { ModusWcIcon as ModusWcIconElement, defineCustomElement as defineModusWcIcon } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-icon.js";
import { ModusWcInputFeedback as ModusWcInputFeedbackElement, defineCustomElement as defineModusWcInputFeedback } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-input-feedback.js";
import { ModusWcInputLabel as ModusWcInputLabelElement, defineCustomElement as defineModusWcInputLabel } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-input-label.js";
import { ModusWcLoader as ModusWcLoaderElement, defineCustomElement as defineModusWcLoader } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-loader.js";
import { ModusWcMenuItem as ModusWcMenuItemElement, defineCustomElement as defineModusWcMenuItem } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-menu-item.js";
import { ModusWcMenu as ModusWcMenuElement, defineCustomElement as defineModusWcMenu } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-menu.js";
import { ModusWcModal as ModusWcModalElement, defineCustomElement as defineModusWcModal } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-modal.js";
import { ModusWcNavbar as ModusWcNavbarElement, defineCustomElement as defineModusWcNavbar } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-navbar.js";
import { ModusWcNumberInput as ModusWcNumberInputElement, defineCustomElement as defineModusWcNumberInput } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-number-input.js";
import { ModusWcPagination as ModusWcPaginationElement, defineCustomElement as defineModusWcPagination } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-pagination.js";
import { ModusWcProgress as ModusWcProgressElement, defineCustomElement as defineModusWcProgress } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-progress.js";
import { ModusWcRadio as ModusWcRadioElement, defineCustomElement as defineModusWcRadio } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-radio.js";
import { ModusWcRating as ModusWcRatingElement, defineCustomElement as defineModusWcRating } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-rating.js";
import { ModusWcSelect as ModusWcSelectElement, defineCustomElement as defineModusWcSelect } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-select.js";
import { ModusWcSkeleton as ModusWcSkeletonElement, defineCustomElement as defineModusWcSkeleton } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-skeleton.js";
import { ModusWcSlider as ModusWcSliderElement, defineCustomElement as defineModusWcSlider } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-slider.js";
import { ModusWcStepper as ModusWcStepperElement, defineCustomElement as defineModusWcStepper } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-stepper.js";
import { ModusWcTable as ModusWcTableElement, defineCustomElement as defineModusWcTable } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-table.js";
import { ModusWcTabs as ModusWcTabsElement, defineCustomElement as defineModusWcTabs } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-tabs.js";
import { ModusWcTextInput as ModusWcTextInputElement, defineCustomElement as defineModusWcTextInput } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-text-input.js";
import { ModusWcTextarea as ModusWcTextareaElement, defineCustomElement as defineModusWcTextarea } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-textarea.js";
import { ModusWcThemeProvider as ModusWcThemeProviderElement, defineCustomElement as defineModusWcThemeProvider } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-theme-provider.js";
import { ModusWcThemeSwitcher as ModusWcThemeSwitcherElement, defineCustomElement as defineModusWcThemeSwitcher } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-theme-switcher.js";
import { ModusWcTimeInput as ModusWcTimeInputElement, defineCustomElement as defineModusWcTimeInput } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-time-input.js";
import { ModusWcToast as ModusWcToastElement, defineCustomElement as defineModusWcToast } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-toast.js";
import { ModusWcToggle as ModusWcToggleElement, defineCustomElement as defineModusWcToggle } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-toggle.js";
import { ModusWcToolbar as ModusWcToolbarElement, defineCustomElement as defineModusWcToolbar } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-toolbar.js";
import { ModusWcTooltip as ModusWcTooltipElement, defineCustomElement as defineModusWcTooltip } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-tooltip.js";
import { ModusWcTypography as ModusWcTypographyElement, defineCustomElement as defineModusWcTypography } from "@trimble-oss/moduswebcomponents/dist/components/modus-wc-typography.js";
import React from 'react';

type ModusWcAccordionEvents = {
    onExpandedChange: EventName<CustomEvent<{
        expanded: boolean;
        index: number;
    }>>
};

export const ModusWcAccordion: StencilReactComponent<ModusWcAccordionElement, ModusWcAccordionEvents> = /*@__PURE__*/ createComponent<ModusWcAccordionElement, ModusWcAccordionEvents>({
    tagName: 'modus-wc-accordion',
    elementClass: ModusWcAccordionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onExpandedChange: 'expandedChange' } as ModusWcAccordionEvents,
    defineCustomElement: defineModusWcAccordion
});

type ModusWcAlertEvents = { onDismissClick: EventName<CustomEvent<any>> };

export const ModusWcAlert: StencilReactComponent<ModusWcAlertElement, ModusWcAlertEvents> = /*@__PURE__*/ createComponent<ModusWcAlertElement, ModusWcAlertEvents>({
    tagName: 'modus-wc-alert',
    elementClass: ModusWcAlertElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDismissClick: 'dismissClick' } as ModusWcAlertEvents,
    defineCustomElement: defineModusWcAlert
});

type ModusWcAutocompleteEvents = {
    onChipRemove: EventName<ModusWcAutocompleteCustomEvent<IAutocompleteItem>>,
    onInputBlur: EventName<ModusWcAutocompleteCustomEvent<FocusEvent>>,
    onInputChange: EventName<ModusWcAutocompleteCustomEvent<Event>>,
    onInputFocus: EventName<ModusWcAutocompleteCustomEvent<FocusEvent>>,
    onItemSelect: EventName<ModusWcAutocompleteCustomEvent<IAutocompleteItem>>
};

export const ModusWcAutocomplete: StencilReactComponent<ModusWcAutocompleteElement, ModusWcAutocompleteEvents> = /*@__PURE__*/ createComponent<ModusWcAutocompleteElement, ModusWcAutocompleteEvents>({
    tagName: 'modus-wc-autocomplete',
    elementClass: ModusWcAutocompleteElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChipRemove: 'chipRemove',
        onInputBlur: 'inputBlur',
        onInputChange: 'inputChange',
        onInputFocus: 'inputFocus',
        onItemSelect: 'itemSelect'
    } as ModusWcAutocompleteEvents,
    defineCustomElement: defineModusWcAutocomplete
});

type ModusWcAvatarEvents = NonNullable<unknown>;

export const ModusWcAvatar: StencilReactComponent<ModusWcAvatarElement, ModusWcAvatarEvents> = /*@__PURE__*/ createComponent<ModusWcAvatarElement, ModusWcAvatarEvents>({
    tagName: 'modus-wc-avatar',
    elementClass: ModusWcAvatarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcAvatarEvents,
    defineCustomElement: defineModusWcAvatar
});

type ModusWcBadgeEvents = NonNullable<unknown>;

export const ModusWcBadge: StencilReactComponent<ModusWcBadgeElement, ModusWcBadgeEvents> = /*@__PURE__*/ createComponent<ModusWcBadgeElement, ModusWcBadgeEvents>({
    tagName: 'modus-wc-badge',
    elementClass: ModusWcBadgeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcBadgeEvents,
    defineCustomElement: defineModusWcBadge
});

type ModusWcBreadcrumbsEvents = { onBreadcrumbClick: EventName<ModusWcBreadcrumbsCustomEvent<IBreadcrumb>> };

export const ModusWcBreadcrumbs: StencilReactComponent<ModusWcBreadcrumbsElement, ModusWcBreadcrumbsEvents> = /*@__PURE__*/ createComponent<ModusWcBreadcrumbsElement, ModusWcBreadcrumbsEvents>({
    tagName: 'modus-wc-breadcrumbs',
    elementClass: ModusWcBreadcrumbsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onBreadcrumbClick: 'breadcrumbClick' } as ModusWcBreadcrumbsEvents,
    defineCustomElement: defineModusWcBreadcrumbs
});

type ModusWcButtonEvents = { onButtonClick: EventName<ModusWcButtonCustomEvent<MouseEvent | KeyboardEvent>> };

export const ModusWcButton: StencilReactComponent<ModusWcButtonElement, ModusWcButtonEvents> = /*@__PURE__*/ createComponent<ModusWcButtonElement, ModusWcButtonEvents>({
    tagName: 'modus-wc-button',
    elementClass: ModusWcButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onButtonClick: 'buttonClick' } as ModusWcButtonEvents,
    defineCustomElement: defineModusWcButton
});

type ModusWcCardEvents = NonNullable<unknown>;

export const ModusWcCard: StencilReactComponent<ModusWcCardElement, ModusWcCardEvents> = /*@__PURE__*/ createComponent<ModusWcCardElement, ModusWcCardEvents>({
    tagName: 'modus-wc-card',
    elementClass: ModusWcCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcCardEvents,
    defineCustomElement: defineModusWcCard
});

type ModusWcCheckboxEvents = {
    onInputBlur: EventName<ModusWcCheckboxCustomEvent<FocusEvent>>,
    onInputChange: EventName<ModusWcCheckboxCustomEvent<InputEvent>>,
    onInputFocus: EventName<ModusWcCheckboxCustomEvent<FocusEvent>>
};

export const ModusWcCheckbox: StencilReactComponent<ModusWcCheckboxElement, ModusWcCheckboxEvents> = /*@__PURE__*/ createComponent<ModusWcCheckboxElement, ModusWcCheckboxEvents>({
    tagName: 'modus-wc-checkbox',
    elementClass: ModusWcCheckboxElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputBlur: 'inputBlur',
        onInputChange: 'inputChange',
        onInputFocus: 'inputFocus'
    } as ModusWcCheckboxEvents,
    defineCustomElement: defineModusWcCheckbox
});

type ModusWcChipEvents = {
    onChipClick: EventName<ModusWcChipCustomEvent<MouseEvent | KeyboardEvent>>,
    onChipRemove: EventName<ModusWcChipCustomEvent<MouseEvent | KeyboardEvent>>
};

export const ModusWcChip: StencilReactComponent<ModusWcChipElement, ModusWcChipEvents> = /*@__PURE__*/ createComponent<ModusWcChipElement, ModusWcChipEvents>({
    tagName: 'modus-wc-chip',
    elementClass: ModusWcChipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChipClick: 'chipClick',
        onChipRemove: 'chipRemove'
    } as ModusWcChipEvents,
    defineCustomElement: defineModusWcChip
});

type ModusWcCollapseEvents = { onExpandedChange: EventName<CustomEvent<{ expanded: boolean }>> };

export const ModusWcCollapse: StencilReactComponent<ModusWcCollapseElement, ModusWcCollapseEvents> = /*@__PURE__*/ createComponent<ModusWcCollapseElement, ModusWcCollapseEvents>({
    tagName: 'modus-wc-collapse',
    elementClass: ModusWcCollapseElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onExpandedChange: 'expandedChange' } as ModusWcCollapseEvents,
    defineCustomElement: defineModusWcCollapse
});

type ModusWcDateEvents = {
    onInputBlur: EventName<ModusWcDateCustomEvent<FocusEvent>>,
    onInputChange: EventName<ModusWcDateCustomEvent<InputEvent>>,
    onInputFocus: EventName<ModusWcDateCustomEvent<FocusEvent>>
};

export const ModusWcDate: StencilReactComponent<ModusWcDateElement, ModusWcDateEvents> = /*@__PURE__*/ createComponent<ModusWcDateElement, ModusWcDateEvents>({
    tagName: 'modus-wc-date',
    elementClass: ModusWcDateElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputBlur: 'inputBlur',
        onInputChange: 'inputChange',
        onInputFocus: 'inputFocus'
    } as ModusWcDateEvents,
    defineCustomElement: defineModusWcDate
});

type ModusWcDividerEvents = NonNullable<unknown>;

export const ModusWcDivider: StencilReactComponent<ModusWcDividerElement, ModusWcDividerEvents> = /*@__PURE__*/ createComponent<ModusWcDividerElement, ModusWcDividerEvents>({
    tagName: 'modus-wc-divider',
    elementClass: ModusWcDividerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcDividerEvents,
    defineCustomElement: defineModusWcDivider
});

type ModusWcIconEvents = NonNullable<unknown>;

export const ModusWcIcon: StencilReactComponent<ModusWcIconElement, ModusWcIconEvents> = /*@__PURE__*/ createComponent<ModusWcIconElement, ModusWcIconEvents>({
    tagName: 'modus-wc-icon',
    elementClass: ModusWcIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcIconEvents,
    defineCustomElement: defineModusWcIcon
});

type ModusWcInputFeedbackEvents = NonNullable<unknown>;

export const ModusWcInputFeedback: StencilReactComponent<ModusWcInputFeedbackElement, ModusWcInputFeedbackEvents> = /*@__PURE__*/ createComponent<ModusWcInputFeedbackElement, ModusWcInputFeedbackEvents>({
    tagName: 'modus-wc-input-feedback',
    elementClass: ModusWcInputFeedbackElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcInputFeedbackEvents,
    defineCustomElement: defineModusWcInputFeedback
});

type ModusWcInputLabelEvents = NonNullable<unknown>;

export const ModusWcInputLabel: StencilReactComponent<ModusWcInputLabelElement, ModusWcInputLabelEvents> = /*@__PURE__*/ createComponent<ModusWcInputLabelElement, ModusWcInputLabelEvents>({
    tagName: 'modus-wc-input-label',
    elementClass: ModusWcInputLabelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcInputLabelEvents,
    defineCustomElement: defineModusWcInputLabel
});

type ModusWcLoaderEvents = NonNullable<unknown>;

export const ModusWcLoader: StencilReactComponent<ModusWcLoaderElement, ModusWcLoaderEvents> = /*@__PURE__*/ createComponent<ModusWcLoaderElement, ModusWcLoaderEvents>({
    tagName: 'modus-wc-loader',
    elementClass: ModusWcLoaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcLoaderEvents,
    defineCustomElement: defineModusWcLoader
});

type ModusWcMenuEvents = NonNullable<unknown>;

export const ModusWcMenu: StencilReactComponent<ModusWcMenuElement, ModusWcMenuEvents> = /*@__PURE__*/ createComponent<ModusWcMenuElement, ModusWcMenuEvents>({
    tagName: 'modus-wc-menu',
    elementClass: ModusWcMenuElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcMenuEvents,
    defineCustomElement: defineModusWcMenu
});

type ModusWcMenuItemEvents = { onItemSelect: EventName<CustomEvent<{ value: string }>> };

export const ModusWcMenuItem: StencilReactComponent<ModusWcMenuItemElement, ModusWcMenuItemEvents> = /*@__PURE__*/ createComponent<ModusWcMenuItemElement, ModusWcMenuItemEvents>({
    tagName: 'modus-wc-menu-item',
    elementClass: ModusWcMenuItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onItemSelect: 'itemSelect' } as ModusWcMenuItemEvents,
    defineCustomElement: defineModusWcMenuItem
});

type ModusWcModalEvents = NonNullable<unknown>;

export const ModusWcModal: StencilReactComponent<ModusWcModalElement, ModusWcModalEvents> = /*@__PURE__*/ createComponent<ModusWcModalElement, ModusWcModalEvents>({
    tagName: 'modus-wc-modal',
    elementClass: ModusWcModalElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcModalEvents,
    defineCustomElement: defineModusWcModal
});

type ModusWcNavbarEvents = {
    onAppsClick: EventName<ModusWcNavbarCustomEvent<MouseEvent | KeyboardEvent>>,
    onHelpClick: EventName<ModusWcNavbarCustomEvent<MouseEvent | KeyboardEvent>>,
    onMyTrimbleClick: EventName<ModusWcNavbarCustomEvent<MouseEvent | KeyboardEvent>>,
    onNotificationsClick: EventName<ModusWcNavbarCustomEvent<MouseEvent | KeyboardEvent>>,
    onSearchChange: EventName<CustomEvent<{ value: string }>>,
    onSearchClick: EventName<ModusWcNavbarCustomEvent<MouseEvent | KeyboardEvent>>,
    onSignOutClick: EventName<ModusWcNavbarCustomEvent<MouseEvent | KeyboardEvent>>,
    onTrimbleLogoClick: EventName<ModusWcNavbarCustomEvent<MouseEvent | KeyboardEvent>>
};

export const ModusWcNavbar: StencilReactComponent<ModusWcNavbarElement, ModusWcNavbarEvents> = /*@__PURE__*/ createComponent<ModusWcNavbarElement, ModusWcNavbarEvents>({
    tagName: 'modus-wc-navbar',
    elementClass: ModusWcNavbarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onAppsClick: 'appsClick',
        onHelpClick: 'helpClick',
        onMyTrimbleClick: 'myTrimbleClick',
        onNotificationsClick: 'notificationsClick',
        onSearchChange: 'searchChange',
        onSearchClick: 'searchClick',
        onSignOutClick: 'signOutClick',
        onTrimbleLogoClick: 'trimbleLogoClick'
    } as ModusWcNavbarEvents,
    defineCustomElement: defineModusWcNavbar
});

type ModusWcNumberInputEvents = {
    onInputBlur: EventName<ModusWcNumberInputCustomEvent<FocusEvent>>,
    onInputChange: EventName<ModusWcNumberInputCustomEvent<InputEvent>>,
    onInputFocus: EventName<ModusWcNumberInputCustomEvent<FocusEvent>>
};

export const ModusWcNumberInput: StencilReactComponent<ModusWcNumberInputElement, ModusWcNumberInputEvents> = /*@__PURE__*/ createComponent<ModusWcNumberInputElement, ModusWcNumberInputEvents>({
    tagName: 'modus-wc-number-input',
    elementClass: ModusWcNumberInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputBlur: 'inputBlur',
        onInputChange: 'inputChange',
        onInputFocus: 'inputFocus'
    } as ModusWcNumberInputEvents,
    defineCustomElement: defineModusWcNumberInput
});

type ModusWcPaginationEvents = { onPageChange: EventName<ModusWcPaginationCustomEvent<IPageChange>> };

export const ModusWcPagination: StencilReactComponent<ModusWcPaginationElement, ModusWcPaginationEvents> = /*@__PURE__*/ createComponent<ModusWcPaginationElement, ModusWcPaginationEvents>({
    tagName: 'modus-wc-pagination',
    elementClass: ModusWcPaginationElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onPageChange: 'pageChange' } as ModusWcPaginationEvents,
    defineCustomElement: defineModusWcPagination
});

type ModusWcProgressEvents = NonNullable<unknown>;

export const ModusWcProgress: StencilReactComponent<ModusWcProgressElement, ModusWcProgressEvents> = /*@__PURE__*/ createComponent<ModusWcProgressElement, ModusWcProgressEvents>({
    tagName: 'modus-wc-progress',
    elementClass: ModusWcProgressElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcProgressEvents,
    defineCustomElement: defineModusWcProgress
});

type ModusWcRadioEvents = {
    onInputBlur: EventName<ModusWcRadioCustomEvent<FocusEvent>>,
    onInputChange: EventName<ModusWcRadioCustomEvent<InputEvent>>,
    onInputFocus: EventName<ModusWcRadioCustomEvent<FocusEvent>>
};

export const ModusWcRadio: StencilReactComponent<ModusWcRadioElement, ModusWcRadioEvents> = /*@__PURE__*/ createComponent<ModusWcRadioElement, ModusWcRadioEvents>({
    tagName: 'modus-wc-radio',
    elementClass: ModusWcRadioElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputBlur: 'inputBlur',
        onInputChange: 'inputChange',
        onInputFocus: 'inputFocus'
    } as ModusWcRadioEvents,
    defineCustomElement: defineModusWcRadio
});

type ModusWcRatingEvents = { onRatingChange: EventName<ModusWcRatingCustomEvent<IRatingChange>> };

export const ModusWcRating: StencilReactComponent<ModusWcRatingElement, ModusWcRatingEvents> = /*@__PURE__*/ createComponent<ModusWcRatingElement, ModusWcRatingEvents>({
    tagName: 'modus-wc-rating',
    elementClass: ModusWcRatingElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onRatingChange: 'ratingChange' } as ModusWcRatingEvents,
    defineCustomElement: defineModusWcRating
});

type ModusWcSelectEvents = {
    onInputBlur: EventName<ModusWcSelectCustomEvent<FocusEvent>>,
    onInputChange: EventName<ModusWcSelectCustomEvent<InputEvent>>,
    onInputFocus: EventName<ModusWcSelectCustomEvent<FocusEvent>>
};

export const ModusWcSelect: StencilReactComponent<ModusWcSelectElement, ModusWcSelectEvents> = /*@__PURE__*/ createComponent<ModusWcSelectElement, ModusWcSelectEvents>({
    tagName: 'modus-wc-select',
    elementClass: ModusWcSelectElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputBlur: 'inputBlur',
        onInputChange: 'inputChange',
        onInputFocus: 'inputFocus'
    } as ModusWcSelectEvents,
    defineCustomElement: defineModusWcSelect
});

type ModusWcSkeletonEvents = NonNullable<unknown>;

export const ModusWcSkeleton: StencilReactComponent<ModusWcSkeletonElement, ModusWcSkeletonEvents> = /*@__PURE__*/ createComponent<ModusWcSkeletonElement, ModusWcSkeletonEvents>({
    tagName: 'modus-wc-skeleton',
    elementClass: ModusWcSkeletonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcSkeletonEvents,
    defineCustomElement: defineModusWcSkeleton
});

type ModusWcSliderEvents = {
    onInputBlur: EventName<ModusWcSliderCustomEvent<FocusEvent>>,
    onInputChange: EventName<ModusWcSliderCustomEvent<InputEvent>>,
    onInputFocus: EventName<ModusWcSliderCustomEvent<FocusEvent>>
};

export const ModusWcSlider: StencilReactComponent<ModusWcSliderElement, ModusWcSliderEvents> = /*@__PURE__*/ createComponent<ModusWcSliderElement, ModusWcSliderEvents>({
    tagName: 'modus-wc-slider',
    elementClass: ModusWcSliderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputBlur: 'inputBlur',
        onInputChange: 'inputChange',
        onInputFocus: 'inputFocus'
    } as ModusWcSliderEvents,
    defineCustomElement: defineModusWcSlider
});

type ModusWcStepperEvents = NonNullable<unknown>;

export const ModusWcStepper: StencilReactComponent<ModusWcStepperElement, ModusWcStepperEvents> = /*@__PURE__*/ createComponent<ModusWcStepperElement, ModusWcStepperEvents>({
    tagName: 'modus-wc-stepper',
    elementClass: ModusWcStepperElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcStepperEvents,
    defineCustomElement: defineModusWcStepper
});

type ModusWcTableEvents = {
    onRowClick: EventName<ModusWcTableCustomEvent<{
        row: Record<string, any>;
        index: number;
    }>>
};

export const ModusWcTable: StencilReactComponent<ModusWcTableElement, ModusWcTableEvents> = /*@__PURE__*/ createComponent<ModusWcTableElement, ModusWcTableEvents>({
    tagName: 'modus-wc-table',
    elementClass: ModusWcTableElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onRowClick: 'rowClick' } as ModusWcTableEvents,
    defineCustomElement: defineModusWcTable
});

type ModusWcTabsEvents = {
    onTabChange: EventName<CustomEvent<{
        previousTab: number;
        newTab: number;
    }>>
};

export const ModusWcTabs: StencilReactComponent<ModusWcTabsElement, ModusWcTabsEvents> = /*@__PURE__*/ createComponent<ModusWcTabsElement, ModusWcTabsEvents>({
    tagName: 'modus-wc-tabs',
    elementClass: ModusWcTabsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onTabChange: 'tabChange' } as ModusWcTabsEvents,
    defineCustomElement: defineModusWcTabs
});

type ModusWcTextInputEvents = {
    onInputBlur: EventName<ModusWcTextInputCustomEvent<FocusEvent>>,
    onInputChange: EventName<ModusWcTextInputCustomEvent<InputEvent>>,
    onInputFocus: EventName<ModusWcTextInputCustomEvent<FocusEvent>>
};

export const ModusWcTextInput: StencilReactComponent<ModusWcTextInputElement, ModusWcTextInputEvents> = /*@__PURE__*/ createComponent<ModusWcTextInputElement, ModusWcTextInputEvents>({
    tagName: 'modus-wc-text-input',
    elementClass: ModusWcTextInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputBlur: 'inputBlur',
        onInputChange: 'inputChange',
        onInputFocus: 'inputFocus'
    } as ModusWcTextInputEvents,
    defineCustomElement: defineModusWcTextInput
});

type ModusWcTextareaEvents = {
    onInputBlur: EventName<ModusWcTextareaCustomEvent<FocusEvent>>,
    onInputChange: EventName<ModusWcTextareaCustomEvent<InputEvent>>,
    onInputFocus: EventName<ModusWcTextareaCustomEvent<FocusEvent>>
};

export const ModusWcTextarea: StencilReactComponent<ModusWcTextareaElement, ModusWcTextareaEvents> = /*@__PURE__*/ createComponent<ModusWcTextareaElement, ModusWcTextareaEvents>({
    tagName: 'modus-wc-textarea',
    elementClass: ModusWcTextareaElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputBlur: 'inputBlur',
        onInputChange: 'inputChange',
        onInputFocus: 'inputFocus'
    } as ModusWcTextareaEvents,
    defineCustomElement: defineModusWcTextarea
});

type ModusWcThemeProviderEvents = NonNullable<unknown>;

export const ModusWcThemeProvider: StencilReactComponent<ModusWcThemeProviderElement, ModusWcThemeProviderEvents> = /*@__PURE__*/ createComponent<ModusWcThemeProviderElement, ModusWcThemeProviderEvents>({
    tagName: 'modus-wc-theme-provider',
    elementClass: ModusWcThemeProviderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcThemeProviderEvents,
    defineCustomElement: defineModusWcThemeProvider
});

type ModusWcThemeSwitcherEvents = { onThemeChange: EventName<ModusWcThemeSwitcherCustomEvent<IThemeConfig>> };

export const ModusWcThemeSwitcher: StencilReactComponent<ModusWcThemeSwitcherElement, ModusWcThemeSwitcherEvents> = /*@__PURE__*/ createComponent<ModusWcThemeSwitcherElement, ModusWcThemeSwitcherEvents>({
    tagName: 'modus-wc-theme-switcher',
    elementClass: ModusWcThemeSwitcherElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onThemeChange: 'themeChange' } as ModusWcThemeSwitcherEvents,
    defineCustomElement: defineModusWcThemeSwitcher
});

type ModusWcTimeInputEvents = {
    onInputBlur: EventName<ModusWcTimeInputCustomEvent<FocusEvent>>,
    onInputChange: EventName<ModusWcTimeInputCustomEvent<Event>>,
    onInputFocus: EventName<ModusWcTimeInputCustomEvent<FocusEvent>>
};

export const ModusWcTimeInput: StencilReactComponent<ModusWcTimeInputElement, ModusWcTimeInputEvents> = /*@__PURE__*/ createComponent<ModusWcTimeInputElement, ModusWcTimeInputEvents>({
    tagName: 'modus-wc-time-input',
    elementClass: ModusWcTimeInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputBlur: 'inputBlur',
        onInputChange: 'inputChange',
        onInputFocus: 'inputFocus'
    } as ModusWcTimeInputEvents,
    defineCustomElement: defineModusWcTimeInput
});

type ModusWcToastEvents = NonNullable<unknown>;

export const ModusWcToast: StencilReactComponent<ModusWcToastElement, ModusWcToastEvents> = /*@__PURE__*/ createComponent<ModusWcToastElement, ModusWcToastEvents>({
    tagName: 'modus-wc-toast',
    elementClass: ModusWcToastElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcToastEvents,
    defineCustomElement: defineModusWcToast
});

type ModusWcToggleEvents = {
    onInputBlur: EventName<ModusWcToggleCustomEvent<FocusEvent>>,
    onInputChange: EventName<ModusWcToggleCustomEvent<InputEvent>>,
    onInputFocus: EventName<ModusWcToggleCustomEvent<FocusEvent>>
};

export const ModusWcToggle: StencilReactComponent<ModusWcToggleElement, ModusWcToggleEvents> = /*@__PURE__*/ createComponent<ModusWcToggleElement, ModusWcToggleEvents>({
    tagName: 'modus-wc-toggle',
    elementClass: ModusWcToggleElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputBlur: 'inputBlur',
        onInputChange: 'inputChange',
        onInputFocus: 'inputFocus'
    } as ModusWcToggleEvents,
    defineCustomElement: defineModusWcToggle
});

type ModusWcToolbarEvents = NonNullable<unknown>;

export const ModusWcToolbar: StencilReactComponent<ModusWcToolbarElement, ModusWcToolbarEvents> = /*@__PURE__*/ createComponent<ModusWcToolbarElement, ModusWcToolbarEvents>({
    tagName: 'modus-wc-toolbar',
    elementClass: ModusWcToolbarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcToolbarEvents,
    defineCustomElement: defineModusWcToolbar
});

type ModusWcTooltipEvents = NonNullable<unknown>;

export const ModusWcTooltip: StencilReactComponent<ModusWcTooltipElement, ModusWcTooltipEvents> = /*@__PURE__*/ createComponent<ModusWcTooltipElement, ModusWcTooltipEvents>({
    tagName: 'modus-wc-tooltip',
    elementClass: ModusWcTooltipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcTooltipEvents,
    defineCustomElement: defineModusWcTooltip
});

type ModusWcTypographyEvents = NonNullable<unknown>;

export const ModusWcTypography: StencilReactComponent<ModusWcTypographyElement, ModusWcTypographyEvents> = /*@__PURE__*/ createComponent<ModusWcTypographyElement, ModusWcTypographyEvents>({
    tagName: 'modus-wc-typography',
    elementClass: ModusWcTypographyElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ModusWcTypographyEvents,
    defineCustomElement: defineModusWcTypography
});
