import { resolveValue } from './css-parse.js';
import { DAISY_SLOTS, SLOT_NAMES } from './slots.js';

const HEX = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/;
const RGB = /^rgba?\(/i;

export function isColorValue(value) {
  const v = value.trim();
  return HEX.test(v) || RGB.test(v);
}

export function validateConfig(config, publicTokens) {
  const errors = [];
  if (!config || typeof config !== 'object') {
    return ['Config must be a JSON object'];
  }
  if (!config.name || typeof config.name !== 'string') {
    errors.push(
      'Config "name" must be a non-empty string (used as data-theme prefix)'
    );
  } else if (!/^[a-z][a-z0-9-]*$/.test(config.name)) {
    errors.push('Config "name" must be a lowercase kebab-case identifier');
  }

  const modes = config.tokens;
  if (!modes || typeof modes !== 'object') {
    errors.push(
      'Config "tokens" must be an object with "light" and/or "dark" maps'
    );
    return errors;
  }

  for (const mode of Object.keys(modes)) {
    if (mode !== 'light' && mode !== 'dark') {
      errors.push(`Unknown mode "${mode}" — expected "light" or "dark"`);
      continue;
    }
    const map = modes[mode];
    if (!map || typeof map !== 'object') {
      errors.push(`tokens.${mode} must be an object of token → color`);
      continue;
    }
    for (const [token, value] of Object.entries(map)) {
      if (publicTokens && !publicTokens.has(token)) {
        errors.push(`Unknown token "${token}" in tokens.${mode}`);
      }
      if (typeof value !== 'string' || !isColorValue(value)) {
        errors.push(
          `Token "${token}" in tokens.${mode} must be a hex or rgb() color, got ${JSON.stringify(value)}`
        );
      }
    }
  }
  return errors;
}

export function emitConsumerCss(config) {
  const name = config.name;
  const modes = config.tokens || {};
  const blocks = [];

  for (const mode of ['light', 'dark']) {
    const overrides = modes[mode];
    if (!overrides) continue;
    const theme = `${name}-${mode}`;
    const overrideDecls = Object.entries(overrides)
      .map(([token, value]) => `  ${token}: ${value};`)
      .join('\n');
    const routing = SLOT_NAMES.map((slot) => {
      const token = DAISY_SLOTS[slot];
      return `  --${slot}: var(${token});\n  --fallback-${slot}: var(${token});`;
    }).join('\n');
    blocks.push(
      `[data-theme='${theme}']:root {\n  color-scheme: ${mode};\n${overrideDecls}\n${routing}\n}`
    );
  }

  return `/* Generated by modus-theme. Do not edit. */\n${blocks.join('\n\n')}\n`;
}

export function previewHostCss(config, baseMap, isDark) {
  const mode = isDark ? 'dark' : 'light';
  const overrides = (config.tokens && config.tokens[mode]) || {};
  const map = new Map(baseMap);
  for (const [token, value] of Object.entries(overrides)) {
    map.set(token, value);
  }
  const decls = SLOT_NAMES.map((slot) => {
    const token = DAISY_SLOTS[slot];
    const hex = resolveValue(`var(${token})`, map, isDark);
    return `--${slot}: ${hex}; --fallback-${slot}: ${hex}; ${token}: ${hex};`;
  });
  return decls.join(' ');
}
