import { resolveValue } from './css-parse.js';
import { hexToOklchChannels } from './oklch.js';
import { DAISY_SLOTS, SLOT_NAMES } from './slots.js';
import {
  isBrandColorToken,
  isCssOverrideValue,
  lockedColorMessage,
} from './token-policy.js';

export function validateConfig(config, publicTokens) {
  const errors = [];
  if (!config || typeof config !== 'object') {
    return ['Config must be a JSON object'];
  }
  if (!config.name || typeof config.name !== 'string') {
    errors.push(
      'Config "name" must be a non-empty string (used as data-theme prefix)'
    );
  } else if (!/^[a-z][a-z0-9-]*$/.test(config.name)) {
    errors.push('Config "name" must be a lowercase kebab-case identifier');
  }

  const modes = config.tokens;
  if (!modes || typeof modes !== 'object') {
    errors.push(
      'Config "tokens" must be an object with "light" and/or "dark" maps'
    );
    return errors;
  }

  for (const mode of Object.keys(modes)) {
    if (mode !== 'light' && mode !== 'dark') {
      errors.push(`Unknown mode "${mode}" — expected "light" or "dark"`);
      continue;
    }
    const map = modes[mode];
    if (!map || typeof map !== 'object') {
      errors.push(`tokens.${mode} must be an object of token → value`);
      continue;
    }
    for (const [token, value] of Object.entries(map)) {
      if (isBrandColorToken(token)) {
        errors.push(lockedColorMessage(token, mode));
        continue;
      }
      if (publicTokens && !publicTokens.has(token)) {
        errors.push(
          `Token "${token}" in tokens.${mode} is not in the public allowlist (non-color --modus-wc-* only)`
        );
      }
      if (!isCssOverrideValue(value)) {
        errors.push(
          `Token "${token}" in tokens.${mode} must be a CSS value without { } or ;, got ${JSON.stringify(value)}`
        );
      }
    }
  }
  return errors;
}

export function emitConsumerCss(config) {
  const name = config.name;
  const modes = config.tokens || {};
  const blocks = [];

  for (const mode of ['light', 'dark']) {
    const overrides = modes[mode];
    if (!overrides) continue;
    const theme = `${name}-${mode}`;
    const overrideDecls = Object.entries(overrides)
      .map(([token, value]) => `  ${token}: ${value};`)
      .join('\n');
    const routing = SLOT_NAMES.map((slot) => {
      const token = DAISY_SLOTS[slot];
      return `  --${slot}: var(${token});\n  --fallback-${slot}: var(${token});`;
    }).join('\n');
    blocks.push(
      `[data-theme='${theme}']:root {\n  color-scheme: ${mode};\n${overrideDecls}\n${routing}\n}`
    );
  }

  return `/* Generated by modus-theme. Do not edit. */\n${blocks.join('\n\n')}\n`;
}

export function extendedThemeName(config, mode) {
  const base = config.extends || 'modus-modern';
  return `${base}-${mode}`;
}

const TOKEN_TO_SLOT = Object.fromEntries(
  SLOT_NAMES.map((slot) => [DAISY_SLOTS[slot], slot])
);

/** Overlay hex tokens onto a built-in Daisy theme so `oklch(var(--p)/1)` stays valid. */
export function emitPreviewOverlayCss(config, mode) {
  const tokens = (config.tokens && config.tokens[mode]) || {};
  const theme = extendedThemeName(config, mode);
  const decls = [];
  for (const [token, value] of Object.entries(tokens)) {
    decls.push(`  ${token}: ${value};`);
    if (token === '--modus-wc-border-radius-btn') {
      decls.push(`  --rounded-btn: ${value};`);
    }
    const slot = TOKEN_TO_SLOT[token];
    if (!slot) continue;
    const channels = hexToOklchChannels(value);
    if (!channels) continue;
    decls.push(`  --${slot}: ${channels};`);
    decls.push(`  --fallback-${slot}: ${value};`);
  }
  return `[data-theme='${theme}']:root {\n${decls.join('\n')}\n}\n`;
}

export function previewHostCss(config, baseMap, isDark) {
  const mode = isDark ? 'dark' : 'light';
  const overrides = (config.tokens && config.tokens[mode]) || {};
  const map = new Map(baseMap);
  for (const [token, value] of Object.entries(overrides)) {
    map.set(token, value);
  }
  const decls = SLOT_NAMES.map((slot) => {
    const token = DAISY_SLOTS[slot];
    const hex = resolveValue(`var(${token})`, map, isDark);
    return `--${slot}: ${hex}; --fallback-${slot}: ${hex}; ${token}: ${hex};`;
  });
  return decls.join(' ');
}
