/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Event } from "@stencil/core";
import { TypographyBodySize, TypographyVariant } from "./components/atoms/modus-wc-typography/modus-wc-typography";
export { Event } from "@stencil/core";
export { TypographyBodySize, TypographyVariant } from "./components/atoms/modus-wc-typography/modus-wc-typography";
export namespace Components {
    /**
     * A customizable avatar component used to create avatars with different images.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcAvatar {
        /**
          * The image alt attribute for accessibility.
         */
        "alt": string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the outer div.
         */
        "customClass": string;
        /**
          * DaisyUI CSS class to apply to inner div.
         */
        "daisyClass": string;
        /**
          * The location of the image.
         */
        "imgSrc": string;
    }
    /**
     * A customizable badge component used to create badges with different sizes, types, and colors.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcBadge {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the badge.
         */
        "color": | 'primary'
    | 'secondary'
    | 'tertiary'
    | 'success'
    | 'warning'
    | 'danger';
        /**
          * The content to display inside the badge. For 'counter' type, this should be a number.
         */
        "content": string;
        /**
          * Custom CSS class to apply to the span element.
         */
        "customClass": string;
        /**
          * The size of the badge.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The type of the badge.
         */
        "type": 'filled' | 'text' | 'counter';
    }
    /**
     * A customizable button component used to create buttons with different sizes, variants, and types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcButton {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the button. Can be 'primary', 'secondary', or 'tertiary'.
         */
        "color": 'primary' | 'secondary' | 'tertiary';
        /**
          * Custom CSS class to apply to the button element.
         */
        "customClass": string;
        /**
          * If true, the button will be disabled.
         */
        "disabled": boolean;
        /**
          * If true, the button will take the full width of its container.
         */
        "fullWidth": boolean;
        /**
          * The text label displayed on the button.
         */
        "label": string;
        /**
          * If true, the button will be in a pressed state (for toggle buttons).
         */
        "pressed": boolean;
        /**
          * The size of the button. Can be 'small', 'medium', or 'large'.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The type of the button. Can be 'button', 'submit', or 'reset'.
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * The variant of the button. Can be 'filled', 'outlined', or 'text'.
         */
        "variant": 'filled' | 'outlined' | 'text';
    }
    /**
     * A customizable divider component used to separate content horizontally or vertically.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcDivider {
        /**
          * The aria-label attribute used for accessibility.
         */
        "ariaLabel": string;
        /**
          * The content to display in the divider.
         */
        "content"?: string;
        /**
          * Custom CSS class to apply to the outer div.
         */
        "customClass": string;
        /**
          * DaisyUI CSS class to apply to the inner div.
         */
        "daisyClass": string;
    }
    /**
     * A customizable input component used to create inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcInput {
        /**
          * The ID of the element that describes the input.
         */
        "ariaDescribedby"?: string;
        /**
          * Indicates whether the input has an invalid input.
         */
        "ariaInvalid"?: boolean;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the input (supports DaisyUI).
         */
        "customClass": string;
        /**
          * Specifies the text direction of the input content.
         */
        "dir"?: 'ltr' | 'rtl' | 'auto';
        /**
          * The disabled state of the input.
         */
        "disabled": boolean;
        /**
          * The ID of the input element.
         */
        "id"?: string;
        /**
          * The maximum number of characters allowed in the input.
         */
        "maxLength"?: number;
        /**
          * The name of the input.
         */
        "name": string;
        /**
          * The input's placeholder text.
         */
        "placeholder": string;
        /**
          * The readonly state of the input.
         */
        "readonly": boolean;
        /**
          * If true, the input will be required.
         */
        "required": boolean;
        /**
          * The tabindex of the input.
         */
        "tabIndex"?: number;
        /**
          * The input's type attribute.
         */
        "type": 'email' | 'number' | 'text' | 'password';
        /**
          * The input's value.
         */
        "value": string;
    }
    /**
     * A customizable textarea component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTextarea {
        /**
          * The ID of the element that describes the textarea.
         */
        "ariaDescribedby"?: string;
        /**
          * Indicates whether the textarea has an invalid input.
         */
        "ariaInvalid"?: boolean;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the textarea (supports DaisyUI).
         */
        "customClass": string;
        /**
          * Specifies the text direction of the textarea content.
         */
        "dir"?: 'ltr' | 'rtl' | 'auto';
        /**
          * The disabled state of the textarea.
         */
        "disabled": boolean;
        /**
          * The ID of the textarea element.
         */
        "id"?: string;
        /**
          * The maximum number of characters allowed in the textarea.
         */
        "maxLength"?: number;
        /**
          * The name of the textarea.
         */
        "name": string;
        /**
          * The placeholder text for the textarea.
         */
        "placeholder": string;
        /**
          * The readonly state of the textarea.
         */
        "readonly": boolean;
        /**
          * The required state of the textarea.
         */
        "required": boolean;
        /**
          * The number of visible text lines for the textarea.
         */
        "rows"?: number;
        /**
          * The tabindex of the textarea.
         */
        "tabIndex"?: number;
        /**
          * The value of the textarea.
         */
        "value": string;
    }
    /**
     * A customizable typography component used to render text with different sizes, variants, weights, and text casing.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTypography {
        /**
          * The aria-label for the typography component.
         */
        "ariaLabel": string;
        /**
          * The size option when variant "body" is selected.
         */
        "bodySize"?: TypographyBodySize;
        /**
          * Custom CSS class to apply to the typography element.
         */
        "customClass": string;
        /**
          * The text case.
         */
        "textCase": 'sentence' | 'title' | 'uppercase';
        /**
          * The variant of the typography component.
         */
        "variant": TypographyVariant;
        /**
          * The weight of the text.
         */
        "weight": 'regular' | 'semibold' | 'bold';
    }
    /**
     * A component used to render auto-generated Stencil documentation in Storybook stories.
     * Searches for the component directory within `/atoms`, `/molecules`, and `organisms`. Renders the `readme.md` file.
     */
    interface StencilDocs {
        /**
          * The component name used to find the proper directory.
         */
        "componentName": string;
    }
}
export interface ModusWcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcButtonElement;
}
export interface ModusWcInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcInputElement;
}
export interface ModusWcTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcTextareaElement;
}
declare global {
    /**
     * A customizable avatar component used to create avatars with different images.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcAvatarElement extends Components.ModusWcAvatar, HTMLStencilElement {
    }
    var HTMLModusWcAvatarElement: {
        prototype: HTMLModusWcAvatarElement;
        new (): HTMLModusWcAvatarElement;
    };
    /**
     * A customizable badge component used to create badges with different sizes, types, and colors.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcBadgeElement extends Components.ModusWcBadge, HTMLStencilElement {
    }
    var HTMLModusWcBadgeElement: {
        prototype: HTMLModusWcBadgeElement;
        new (): HTMLModusWcBadgeElement;
    };
    interface HTMLModusWcButtonElementEventMap {
        "click": MouseEvent | KeyboardEvent;
    }
    /**
     * A customizable button component used to create buttons with different sizes, variants, and types.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcButtonElement extends Components.ModusWcButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcButtonElementEventMap>(type: K, listener: (this: HTMLModusWcButtonElement, ev: ModusWcButtonCustomEvent<HTMLModusWcButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcButtonElementEventMap>(type: K, listener: (this: HTMLModusWcButtonElement, ev: ModusWcButtonCustomEvent<HTMLModusWcButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcButtonElement: {
        prototype: HTMLModusWcButtonElement;
        new (): HTMLModusWcButtonElement;
    };
    /**
     * A customizable divider component used to separate content horizontally or vertically.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcDividerElement extends Components.ModusWcDivider, HTMLStencilElement {
    }
    var HTMLModusWcDividerElement: {
        prototype: HTMLModusWcDividerElement;
        new (): HTMLModusWcDividerElement;
    };
    interface HTMLModusWcInputElementEventMap {
        "blur": FocusEvent;
        "change": Event;
        "focus": FocusEvent;
    }
    /**
     * A customizable input component used to create inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcInputElement extends Components.ModusWcInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcInputElementEventMap>(type: K, listener: (this: HTMLModusWcInputElement, ev: ModusWcInputCustomEvent<HTMLModusWcInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcInputElementEventMap>(type: K, listener: (this: HTMLModusWcInputElement, ev: ModusWcInputCustomEvent<HTMLModusWcInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcInputElement: {
        prototype: HTMLModusWcInputElement;
        new (): HTMLModusWcInputElement;
    };
    interface HTMLModusWcTextareaElementEventMap {
        "blur": FocusEvent;
        "change": Event;
        "focus": FocusEvent;
    }
    /**
     * A customizable textarea component.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcTextareaElement extends Components.ModusWcTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcTextareaElementEventMap>(type: K, listener: (this: HTMLModusWcTextareaElement, ev: ModusWcTextareaCustomEvent<HTMLModusWcTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcTextareaElementEventMap>(type: K, listener: (this: HTMLModusWcTextareaElement, ev: ModusWcTextareaCustomEvent<HTMLModusWcTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcTextareaElement: {
        prototype: HTMLModusWcTextareaElement;
        new (): HTMLModusWcTextareaElement;
    };
    /**
     * A customizable typography component used to render text with different sizes, variants, weights, and text casing.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcTypographyElement extends Components.ModusWcTypography, HTMLStencilElement {
    }
    var HTMLModusWcTypographyElement: {
        prototype: HTMLModusWcTypographyElement;
        new (): HTMLModusWcTypographyElement;
    };
    /**
     * A component used to render auto-generated Stencil documentation in Storybook stories.
     * Searches for the component directory within `/atoms`, `/molecules`, and `organisms`. Renders the `readme.md` file.
     */
    interface HTMLStencilDocsElement extends Components.StencilDocs, HTMLStencilElement {
    }
    var HTMLStencilDocsElement: {
        prototype: HTMLStencilDocsElement;
        new (): HTMLStencilDocsElement;
    };
    interface HTMLElementTagNameMap {
        "modus-wc-avatar": HTMLModusWcAvatarElement;
        "modus-wc-badge": HTMLModusWcBadgeElement;
        "modus-wc-button": HTMLModusWcButtonElement;
        "modus-wc-divider": HTMLModusWcDividerElement;
        "modus-wc-input": HTMLModusWcInputElement;
        "modus-wc-textarea": HTMLModusWcTextareaElement;
        "modus-wc-typography": HTMLModusWcTypographyElement;
        "stencil-docs": HTMLStencilDocsElement;
    }
}
declare namespace LocalJSX {
    /**
     * A customizable avatar component used to create avatars with different images.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcAvatar {
        /**
          * The image alt attribute for accessibility.
         */
        "alt": string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the outer div.
         */
        "customClass"?: string;
        /**
          * DaisyUI CSS class to apply to inner div.
         */
        "daisyClass"?: string;
        /**
          * The location of the image.
         */
        "imgSrc"?: string;
    }
    /**
     * A customizable badge component used to create badges with different sizes, types, and colors.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcBadge {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the badge.
         */
        "color"?: | 'primary'
    | 'secondary'
    | 'tertiary'
    | 'success'
    | 'warning'
    | 'danger';
        /**
          * The content to display inside the badge. For 'counter' type, this should be a number.
         */
        "content": string;
        /**
          * Custom CSS class to apply to the span element.
         */
        "customClass"?: string;
        /**
          * The size of the badge.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The type of the badge.
         */
        "type"?: 'filled' | 'text' | 'counter';
    }
    /**
     * A customizable button component used to create buttons with different sizes, variants, and types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcButton {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the button. Can be 'primary', 'secondary', or 'tertiary'.
         */
        "color"?: 'primary' | 'secondary' | 'tertiary';
        /**
          * Custom CSS class to apply to the button element.
         */
        "customClass"?: string;
        /**
          * If true, the button will be disabled.
         */
        "disabled"?: boolean;
        /**
          * If true, the button will take the full width of its container.
         */
        "fullWidth"?: boolean;
        /**
          * The text label displayed on the button.
         */
        "label": string;
        /**
          * Event emitted when the button is clicked or activated via keyboard.
         */
        "onClick"?: (event: ModusWcButtonCustomEvent<MouseEvent | KeyboardEvent>) => void;
        /**
          * If true, the button will be in a pressed state (for toggle buttons).
         */
        "pressed"?: boolean;
        /**
          * The size of the button. Can be 'small', 'medium', or 'large'.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The type of the button. Can be 'button', 'submit', or 'reset'.
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * The variant of the button. Can be 'filled', 'outlined', or 'text'.
         */
        "variant"?: 'filled' | 'outlined' | 'text';
    }
    /**
     * A customizable divider component used to separate content horizontally or vertically.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcDivider {
        /**
          * The aria-label attribute used for accessibility.
         */
        "ariaLabel": string;
        /**
          * The content to display in the divider.
         */
        "content"?: string;
        /**
          * Custom CSS class to apply to the outer div.
         */
        "customClass"?: string;
        /**
          * DaisyUI CSS class to apply to the inner div.
         */
        "daisyClass"?: string;
    }
    /**
     * A customizable input component used to create inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcInput {
        /**
          * The ID of the element that describes the input.
         */
        "ariaDescribedby"?: string;
        /**
          * Indicates whether the input has an invalid input.
         */
        "ariaInvalid"?: boolean;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the input (supports DaisyUI).
         */
        "customClass"?: string;
        /**
          * Specifies the text direction of the input content.
         */
        "dir"?: 'ltr' | 'rtl' | 'auto';
        /**
          * The disabled state of the input.
         */
        "disabled"?: boolean;
        /**
          * The ID of the input element.
         */
        "id"?: string;
        /**
          * The maximum number of characters allowed in the input.
         */
        "maxLength"?: number;
        /**
          * The name of the input.
         */
        "name"?: string;
        /**
          * Event emitted when the input loses focus.
         */
        "onBlur"?: (event: ModusWcInputCustomEvent<FocusEvent>) => void;
        /**
          * Event emitted when the input value changes.
         */
        "onChange"?: (event: ModusWcInputCustomEvent<Event>) => void;
        /**
          * Event emitted when the input gains focus.
         */
        "onFocus"?: (event: ModusWcInputCustomEvent<FocusEvent>) => void;
        /**
          * The input's placeholder text.
         */
        "placeholder"?: string;
        /**
          * The readonly state of the input.
         */
        "readonly"?: boolean;
        /**
          * If true, the input will be required.
         */
        "required"?: boolean;
        /**
          * The tabindex of the input.
         */
        "tabIndex"?: number;
        /**
          * The input's type attribute.
         */
        "type"?: 'email' | 'number' | 'text' | 'password';
        /**
          * The input's value.
         */
        "value"?: string;
    }
    /**
     * A customizable textarea component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTextarea {
        /**
          * The ID of the element that describes the textarea.
         */
        "ariaDescribedby"?: string;
        /**
          * Indicates whether the textarea has an invalid input.
         */
        "ariaInvalid"?: boolean;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the textarea (supports DaisyUI).
         */
        "customClass"?: string;
        /**
          * Specifies the text direction of the textarea content.
         */
        "dir"?: 'ltr' | 'rtl' | 'auto';
        /**
          * The disabled state of the textarea.
         */
        "disabled"?: boolean;
        /**
          * The ID of the textarea element.
         */
        "id"?: string;
        /**
          * The maximum number of characters allowed in the textarea.
         */
        "maxLength"?: number;
        /**
          * The name of the textarea.
         */
        "name"?: string;
        /**
          * Emitted when the textarea loses focus.
         */
        "onBlur"?: (event: ModusWcTextareaCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the textarea value changes.
         */
        "onChange"?: (event: ModusWcTextareaCustomEvent<Event>) => void;
        /**
          * Emitted when the textarea gains focus.
         */
        "onFocus"?: (event: ModusWcTextareaCustomEvent<FocusEvent>) => void;
        /**
          * The placeholder text for the textarea.
         */
        "placeholder"?: string;
        /**
          * The readonly state of the textarea.
         */
        "readonly"?: boolean;
        /**
          * The required state of the textarea.
         */
        "required"?: boolean;
        /**
          * The number of visible text lines for the textarea.
         */
        "rows"?: number;
        /**
          * The tabindex of the textarea.
         */
        "tabIndex"?: number;
        /**
          * The value of the textarea.
         */
        "value"?: string;
    }
    /**
     * A customizable typography component used to render text with different sizes, variants, weights, and text casing.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTypography {
        /**
          * The aria-label for the typography component.
         */
        "ariaLabel": string;
        /**
          * The size option when variant "body" is selected.
         */
        "bodySize"?: TypographyBodySize;
        /**
          * Custom CSS class to apply to the typography element.
         */
        "customClass"?: string;
        /**
          * The text case.
         */
        "textCase"?: 'sentence' | 'title' | 'uppercase';
        /**
          * The variant of the typography component.
         */
        "variant"?: TypographyVariant;
        /**
          * The weight of the text.
         */
        "weight"?: 'regular' | 'semibold' | 'bold';
    }
    /**
     * A component used to render auto-generated Stencil documentation in Storybook stories.
     * Searches for the component directory within `/atoms`, `/molecules`, and `organisms`. Renders the `readme.md` file.
     */
    interface StencilDocs {
        /**
          * The component name used to find the proper directory.
         */
        "componentName": string;
    }
    interface IntrinsicElements {
        "modus-wc-avatar": ModusWcAvatar;
        "modus-wc-badge": ModusWcBadge;
        "modus-wc-button": ModusWcButton;
        "modus-wc-divider": ModusWcDivider;
        "modus-wc-input": ModusWcInput;
        "modus-wc-textarea": ModusWcTextarea;
        "modus-wc-typography": ModusWcTypography;
        "stencil-docs": StencilDocs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A customizable avatar component used to create avatars with different images.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-avatar": LocalJSX.ModusWcAvatar & JSXBase.HTMLAttributes<HTMLModusWcAvatarElement>;
            /**
             * A customizable badge component used to create badges with different sizes, types, and colors.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-badge": LocalJSX.ModusWcBadge & JSXBase.HTMLAttributes<HTMLModusWcBadgeElement>;
            /**
             * A customizable button component used to create buttons with different sizes, variants, and types.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-button": LocalJSX.ModusWcButton & JSXBase.HTMLAttributes<HTMLModusWcButtonElement>;
            /**
             * A customizable divider component used to separate content horizontally or vertically.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-divider": LocalJSX.ModusWcDivider & JSXBase.HTMLAttributes<HTMLModusWcDividerElement>;
            /**
             * A customizable input component used to create inputs with types.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-input": LocalJSX.ModusWcInput & JSXBase.HTMLAttributes<HTMLModusWcInputElement>;
            /**
             * A customizable textarea component.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-textarea": LocalJSX.ModusWcTextarea & JSXBase.HTMLAttributes<HTMLModusWcTextareaElement>;
            /**
             * A customizable typography component used to render text with different sizes, variants, weights, and text casing.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-typography": LocalJSX.ModusWcTypography & JSXBase.HTMLAttributes<HTMLModusWcTypographyElement>;
            /**
             * A component used to render auto-generated Stencil documentation in Storybook stories.
             * Searches for the component directory within `/atoms`, `/molecules`, and `organisms`. Renders the `readme.md` file.
             */
            "stencil-docs": LocalJSX.StencilDocs & JSXBase.HTMLAttributes<HTMLStencilDocsElement>;
        }
    }
}
