/* eslint-env node */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));

// Read CSS files
const outputCSSPath = join(__dirname, '../src/styles/output.css');
const globalCSSPath = join(__dirname, '../src/styles/global.css');
const iconsCSSPath = join(__dirname, '../src/styles/modus-icons.css');
const targetPath = join(__dirname, '../src/providers/theme/css-content.ts');

let outputCSS = '';
let globalCSS = '';
let iconsCSS = '';

const serializeString = (value) => JSON.stringify(value);

try {
  if (existsSync(outputCSSPath)) {
    outputCSS = readFileSync(outputCSSPath, 'utf8');
  }
} catch (error) {
  globalThis.console.warn('Could not read output.css:', error.message);
}

try {
  if (existsSync(globalCSSPath)) {
    globalCSS = readFileSync(globalCSSPath, 'utf8');
  }
} catch (error) {
  globalThis.console.warn('Could not read global.css:', error.message);
}

try {
  if (existsSync(iconsCSSPath)) {
    iconsCSS = readFileSync(iconsCSSPath, 'utf8');
  }
} catch (error) {
  globalThis.console.warn('Could not read modus-icons.css:', error.message);
}

// Generate the TypeScript file
const content = `// This file is auto-generated by scripts/embed-css.js
// DO NOT EDIT MANUALLY

export const outputCSS = ${serializeString(outputCSS)};

export const globalCSS = ${serializeString(globalCSS)};

export const iconsCSS = ${serializeString(iconsCSS)};
`;

// Write the file
writeFileSync(targetPath, content, 'utf8');
globalThis.console.log('CSS content embedded successfully!');
