import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../src/utils/logger';
const __dirname = dirname(fileURLToPath(import.meta.url));

// Read CSS files
const outputCSSPath = join(__dirname, '../src/styles/output.css');
const globalCSSPath = join(__dirname, '../src/styles/global.css');
const targetPath = join(__dirname, '../src/providers/theme/css-content.ts');

let outputCSS = '';
let globalCSS = '';

try {
  if (existsSync(outputCSSPath)) {
    outputCSS = readFileSync(outputCSSPath, 'utf8');
  }
} catch (error) {
  logger.warn('Could not read output.css:', error.message);
}

try {
  if (existsSync(globalCSSPath)) {
    globalCSS = readFileSync(globalCSSPath, 'utf8');
  }
} catch (error) {
  console.warn('Could not read global.css:', error.message);
}

// Generate the TypeScript file
const content = `// This file is auto-generated by scripts/embed-css.js
// DO NOT EDIT MANUALLY

export const outputCSS = \`${outputCSS.replace(/`/g, '\\`')}\`;

export const globalCSS = \`${globalCSS.replace(/`/g, '\\`')}\`;
`;

// Write the file
writeFileSync(targetPath, content, 'utf8');
console.log('CSS content embedded successfully!');