/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TypographyBodySize, TypographyVariant } from "./components/atoms/modus-wc-typography/modus-wc-typography";
export { TypographyBodySize, TypographyVariant } from "./components/atoms/modus-wc-typography/modus-wc-typography";
export namespace Components {
    /**
     * A customizable avatar component used to create avatars with different images.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcAvatar {
        /**
          * The image alt attribute for accessibility.
         */
        "alt": string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass": string;
        /**
          * The location of the image.
         */
        "imgSrc": string;
        /**
          * The shape of the avatar.
         */
        "shape"?: 'circle' | 'square';
        /**
          * The size of the avatar.
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    /**
     * A customizable badge component used to create badges with different sizes, types, and colors.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcBadge {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the badge.
         */
        "color": | 'primary'
    | 'secondary'
    | 'tertiary'
    | 'success'
    | 'warning'
    | 'danger';
        /**
          * The content to display inside the badge. For 'counter' type, this should be a number.
         */
        "content": string;
        /**
          * Custom CSS class to apply to the span element.
         */
        "customClass": string;
        /**
          * The size of the badge.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The type of the badge.
         */
        "type": 'filled' | 'text' | 'counter';
    }
    /**
     * A customizable button component used to create buttons with different sizes, variants, and types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcButton {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the button. Can be 'primary', 'secondary', or 'tertiary'.
         */
        "color": 'primary' | 'secondary' | 'tertiary';
        /**
          * Custom CSS class to apply to the button element.
         */
        "customClass": string;
        /**
          * If true, the button will be disabled.
         */
        "disabled": boolean;
        /**
          * If true, the button will take the full width of its container.
         */
        "fullWidth": boolean;
        /**
          * The text label displayed on the button.
         */
        "label": string;
        /**
          * If true, the button will be in a pressed state (for toggle buttons).
         */
        "pressed": boolean;
        /**
          * The size of the button. Can be 'small', 'medium', or 'large'.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The type of the button. Can be 'button', 'submit', or 'reset'.
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * The variant of the button. Can be 'filled', 'outlined', or 'text'.
         */
        "variant": 'filled' | 'outlined' | 'text';
    }
    /**
     * A customizable divider component used to separate content horizontally or vertically.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcDivider {
        /**
          * The aria-label attribute used for accessibility.
         */
        "ariaLabel": string;
        /**
          * The content to display in the divider.
         */
        "content"?: string;
        /**
          * Custom CSS class to apply to the outer div.
         */
        "customClass": string;
        /**
          * DaisyUI CSS class to apply to the inner div.
         */
        "daisyClass": string;
    }
    /**
     * A customizable input component used to create text inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTextInput {
        /**
          * The ID of the element that describes the input.
         */
        "ariaDescribedby"?: string;
        /**
          * Indicates whether the input has an invalid input.
         */
        "ariaInvalid": 'true' | 'false';
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Controls automatic capitalization in inputted text.
         */
        "autoCapitalize"?: | 'off'
    | 'none'
    | 'on'
    | 'sentences'
    | 'words'
    | 'characters';
        /**
          * Hint for form autofill feature.
         */
        "autoComplete"?: 'on' | 'off';
        /**
          * Indicates that an element should be focused on page load.
         */
        "autoFocus"?: boolean;
        /**
          * Indicates that the input should have a border.
         */
        "bordered"?: boolean;
        /**
          * Custom CSS class to apply to the input.
         */
        "customClass": string;
        /**
          * Specifies the text direction of the input content.
         */
        "dir": '' | 'ltr' | 'rtl' | 'auto';
        /**
          * Whether the form control is disabled.
         */
        "disabled": boolean;
        /**
          * The ID of the input element.
         */
        "id": string;
        /**
          * Hints at the type of data that might be entered by the user while editing the element or its contents. This allows a browser to display an appropriate virtual keyboard.
         */
        "inputMode": | 'decimal'
    | 'email'
    | 'none'
    | 'numeric'
    | 'search'
    | 'tel'
    | 'text'
    | 'url';
        /**
          * Maximum length (number of characters) of value.
         */
        "maxLength"?: number;
        /**
          * Minimum length (number of characters) of value.
         */
        "minLength"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pai.
         */
        "name": string;
        /**
          * Pattern the value must match to be valid
         */
        "pattern"?: string;
        /**
          * Text that appears in the form control when it has no value set.
         */
        "placeholder": string;
        /**
          * Whether the value is editable.
         */
        "readOnly": boolean;
        /**
          * A value is required or must be checked for the form to be submittable.
         */
        "required": boolean;
        /**
          * The size of the input.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Whether the element may be checked for spelling errors. A hint for the browser, not a guarantee.
         */
        "spellcheck": boolean;
        /**
          * Determine the control's relative ordering for sequential focus navigation (typically with the Tab key).
         */
        "tabIndex": number;
        /**
          * Type of form control.
         */
        "type": 'email' | 'password' | 'search' | 'tel' | 'text' | 'url';
        /**
          * The value of the control.
         */
        "value": string;
    }
    /**
     * A customizable textarea component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTextarea {
        /**
          * The ID of the element that describes the textarea.
         */
        "ariaDescribedby"?: string;
        /**
          * Indicates whether the textarea has an invalid input.
         */
        "ariaInvalid": 'true' | 'false';
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the textarea (supports DaisyUI).
         */
        "customClass": string;
        /**
          * Specifies the text direction of the textarea content.
         */
        "dir": '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The disabled state of the textarea.
         */
        "disabled": boolean;
        /**
          * The ID of the textarea element.
         */
        "id": string;
        /**
          * The maximum number of characters allowed in the textarea.
         */
        "maxLength"?: number;
        /**
          * The name of the textarea.
         */
        "name": string;
        /**
          * The placeholder text for the textarea.
         */
        "placeholder": string;
        /**
          * The readonly state of the textarea.
         */
        "readonly": boolean;
        /**
          * The required state of the textarea.
         */
        "required": boolean;
        /**
          * The number of visible text lines for the textarea.
         */
        "rows"?: number;
        /**
          * The tabindex of the textarea.
         */
        "tabIndex": number;
        /**
          * The value of the textarea.
         */
        "value": string;
    }
    /**
     * A customizable typography component used to render text with different sizes, variants, weights, and text casing.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTypography {
        /**
          * The aria-label for the typography component.
         */
        "ariaLabel": string;
        /**
          * The size option when variant "body" is selected.
         */
        "bodySize"?: TypographyBodySize;
        /**
          * Custom CSS class to apply to the typography element.
         */
        "customClass": string;
        /**
          * The text case.
         */
        "textCase": 'sentence' | 'title' | 'uppercase';
        /**
          * The variant of the typography component.
         */
        "variant": TypographyVariant;
        /**
          * The weight of the text.
         */
        "weight": 'regular' | 'semibold' | 'bold';
    }
    /**
     * A component used to render auto-generated Stencil documentation in Storybook stories.
     * Searches for the component directory within `/atoms`, `/molecules`, and `organisms`. Renders the `readme.md` file.
     */
    interface StencilDocs {
        /**
          * The component name used to find the proper directory.
         */
        "componentName": string;
    }
}
export interface ModusWcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcButtonElement;
}
export interface ModusWcTextInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcTextInputElement;
}
export interface ModusWcTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcTextareaElement;
}
declare global {
    /**
     * A customizable avatar component used to create avatars with different images.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcAvatarElement extends Components.ModusWcAvatar, HTMLStencilElement {
    }
    var HTMLModusWcAvatarElement: {
        prototype: HTMLModusWcAvatarElement;
        new (): HTMLModusWcAvatarElement;
    };
    /**
     * A customizable badge component used to create badges with different sizes, types, and colors.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcBadgeElement extends Components.ModusWcBadge, HTMLStencilElement {
    }
    var HTMLModusWcBadgeElement: {
        prototype: HTMLModusWcBadgeElement;
        new (): HTMLModusWcBadgeElement;
    };
    interface HTMLModusWcButtonElementEventMap {
        "click": MouseEvent | KeyboardEvent;
    }
    /**
     * A customizable button component used to create buttons with different sizes, variants, and types.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcButtonElement extends Components.ModusWcButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcButtonElementEventMap>(type: K, listener: (this: HTMLModusWcButtonElement, ev: ModusWcButtonCustomEvent<HTMLModusWcButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcButtonElementEventMap>(type: K, listener: (this: HTMLModusWcButtonElement, ev: ModusWcButtonCustomEvent<HTMLModusWcButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcButtonElement: {
        prototype: HTMLModusWcButtonElement;
        new (): HTMLModusWcButtonElement;
    };
    /**
     * A customizable divider component used to separate content horizontally or vertically.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcDividerElement extends Components.ModusWcDivider, HTMLStencilElement {
    }
    var HTMLModusWcDividerElement: {
        prototype: HTMLModusWcDividerElement;
        new (): HTMLModusWcDividerElement;
    };
    interface HTMLModusWcTextInputElementEventMap {
        "blur": FocusEvent;
        "change": Event;
        "focus": FocusEvent;
    }
    /**
     * A customizable input component used to create text inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcTextInputElement extends Components.ModusWcTextInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcTextInputElementEventMap>(type: K, listener: (this: HTMLModusWcTextInputElement, ev: ModusWcTextInputCustomEvent<HTMLModusWcTextInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcTextInputElementEventMap>(type: K, listener: (this: HTMLModusWcTextInputElement, ev: ModusWcTextInputCustomEvent<HTMLModusWcTextInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcTextInputElement: {
        prototype: HTMLModusWcTextInputElement;
        new (): HTMLModusWcTextInputElement;
    };
    interface HTMLModusWcTextareaElementEventMap {
        "blur": FocusEvent;
        "change": Event;
        "focus": FocusEvent;
    }
    /**
     * A customizable textarea component.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcTextareaElement extends Components.ModusWcTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcTextareaElementEventMap>(type: K, listener: (this: HTMLModusWcTextareaElement, ev: ModusWcTextareaCustomEvent<HTMLModusWcTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcTextareaElementEventMap>(type: K, listener: (this: HTMLModusWcTextareaElement, ev: ModusWcTextareaCustomEvent<HTMLModusWcTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcTextareaElement: {
        prototype: HTMLModusWcTextareaElement;
        new (): HTMLModusWcTextareaElement;
    };
    /**
     * A customizable typography component used to render text with different sizes, variants, weights, and text casing.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcTypographyElement extends Components.ModusWcTypography, HTMLStencilElement {
    }
    var HTMLModusWcTypographyElement: {
        prototype: HTMLModusWcTypographyElement;
        new (): HTMLModusWcTypographyElement;
    };
    /**
     * A component used to render auto-generated Stencil documentation in Storybook stories.
     * Searches for the component directory within `/atoms`, `/molecules`, and `organisms`. Renders the `readme.md` file.
     */
    interface HTMLStencilDocsElement extends Components.StencilDocs, HTMLStencilElement {
    }
    var HTMLStencilDocsElement: {
        prototype: HTMLStencilDocsElement;
        new (): HTMLStencilDocsElement;
    };
    interface HTMLElementTagNameMap {
        "modus-wc-avatar": HTMLModusWcAvatarElement;
        "modus-wc-badge": HTMLModusWcBadgeElement;
        "modus-wc-button": HTMLModusWcButtonElement;
        "modus-wc-divider": HTMLModusWcDividerElement;
        "modus-wc-text-input": HTMLModusWcTextInputElement;
        "modus-wc-textarea": HTMLModusWcTextareaElement;
        "modus-wc-typography": HTMLModusWcTypographyElement;
        "stencil-docs": HTMLStencilDocsElement;
    }
}
declare namespace LocalJSX {
    /**
     * A customizable avatar component used to create avatars with different images.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcAvatar {
        /**
          * The image alt attribute for accessibility.
         */
        "alt": string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass"?: string;
        /**
          * The location of the image.
         */
        "imgSrc"?: string;
        /**
          * The shape of the avatar.
         */
        "shape"?: 'circle' | 'square';
        /**
          * The size of the avatar.
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    /**
     * A customizable badge component used to create badges with different sizes, types, and colors.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcBadge {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the badge.
         */
        "color"?: | 'primary'
    | 'secondary'
    | 'tertiary'
    | 'success'
    | 'warning'
    | 'danger';
        /**
          * The content to display inside the badge. For 'counter' type, this should be a number.
         */
        "content": string;
        /**
          * Custom CSS class to apply to the span element.
         */
        "customClass"?: string;
        /**
          * The size of the badge.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The type of the badge.
         */
        "type"?: 'filled' | 'text' | 'counter';
    }
    /**
     * A customizable button component used to create buttons with different sizes, variants, and types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcButton {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the button. Can be 'primary', 'secondary', or 'tertiary'.
         */
        "color"?: 'primary' | 'secondary' | 'tertiary';
        /**
          * Custom CSS class to apply to the button element.
         */
        "customClass"?: string;
        /**
          * If true, the button will be disabled.
         */
        "disabled"?: boolean;
        /**
          * If true, the button will take the full width of its container.
         */
        "fullWidth"?: boolean;
        /**
          * The text label displayed on the button.
         */
        "label": string;
        /**
          * Event emitted when the button is clicked or activated via keyboard.
         */
        "onClick"?: (event: ModusWcButtonCustomEvent<MouseEvent | KeyboardEvent>) => void;
        /**
          * If true, the button will be in a pressed state (for toggle buttons).
         */
        "pressed"?: boolean;
        /**
          * The size of the button. Can be 'small', 'medium', or 'large'.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The type of the button. Can be 'button', 'submit', or 'reset'.
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * The variant of the button. Can be 'filled', 'outlined', or 'text'.
         */
        "variant"?: 'filled' | 'outlined' | 'text';
    }
    /**
     * A customizable divider component used to separate content horizontally or vertically.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcDivider {
        /**
          * The aria-label attribute used for accessibility.
         */
        "ariaLabel": string;
        /**
          * The content to display in the divider.
         */
        "content"?: string;
        /**
          * Custom CSS class to apply to the outer div.
         */
        "customClass"?: string;
        /**
          * DaisyUI CSS class to apply to the inner div.
         */
        "daisyClass"?: string;
    }
    /**
     * A customizable input component used to create text inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTextInput {
        /**
          * The ID of the element that describes the input.
         */
        "ariaDescribedby"?: string;
        /**
          * Indicates whether the input has an invalid input.
         */
        "ariaInvalid"?: 'true' | 'false';
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Controls automatic capitalization in inputted text.
         */
        "autoCapitalize"?: | 'off'
    | 'none'
    | 'on'
    | 'sentences'
    | 'words'
    | 'characters';
        /**
          * Hint for form autofill feature.
         */
        "autoComplete"?: 'on' | 'off';
        /**
          * Indicates that an element should be focused on page load.
         */
        "autoFocus"?: boolean;
        /**
          * Indicates that the input should have a border.
         */
        "bordered"?: boolean;
        /**
          * Custom CSS class to apply to the input.
         */
        "customClass"?: string;
        /**
          * Specifies the text direction of the input content.
         */
        "dir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * Whether the form control is disabled.
         */
        "disabled"?: boolean;
        /**
          * The ID of the input element.
         */
        "id"?: string;
        /**
          * Hints at the type of data that might be entered by the user while editing the element or its contents. This allows a browser to display an appropriate virtual keyboard.
         */
        "inputMode"?: | 'decimal'
    | 'email'
    | 'none'
    | 'numeric'
    | 'search'
    | 'tel'
    | 'text'
    | 'url';
        /**
          * Maximum length (number of characters) of value.
         */
        "maxLength"?: number;
        /**
          * Minimum length (number of characters) of value.
         */
        "minLength"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pai.
         */
        "name"?: string;
        /**
          * Event emitted when the input loses focus.
         */
        "onBlur"?: (event: ModusWcTextInputCustomEvent<FocusEvent>) => void;
        /**
          * Event emitted when the input value changes.
         */
        "onChange"?: (event: ModusWcTextInputCustomEvent<Event>) => void;
        /**
          * Event emitted when the input gains focus.
         */
        "onFocus"?: (event: ModusWcTextInputCustomEvent<FocusEvent>) => void;
        /**
          * Pattern the value must match to be valid
         */
        "pattern"?: string;
        /**
          * Text that appears in the form control when it has no value set.
         */
        "placeholder"?: string;
        /**
          * Whether the value is editable.
         */
        "readOnly"?: boolean;
        /**
          * A value is required or must be checked for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Whether the element may be checked for spelling errors. A hint for the browser, not a guarantee.
         */
        "spellcheck"?: boolean;
        /**
          * Determine the control's relative ordering for sequential focus navigation (typically with the Tab key).
         */
        "tabIndex"?: number;
        /**
          * Type of form control.
         */
        "type"?: 'email' | 'password' | 'search' | 'tel' | 'text' | 'url';
        /**
          * The value of the control.
         */
        "value"?: string;
    }
    /**
     * A customizable textarea component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTextarea {
        /**
          * The ID of the element that describes the textarea.
         */
        "ariaDescribedby"?: string;
        /**
          * Indicates whether the textarea has an invalid input.
         */
        "ariaInvalid"?: 'true' | 'false';
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the textarea (supports DaisyUI).
         */
        "customClass"?: string;
        /**
          * Specifies the text direction of the textarea content.
         */
        "dir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The disabled state of the textarea.
         */
        "disabled"?: boolean;
        /**
          * The ID of the textarea element.
         */
        "id"?: string;
        /**
          * The maximum number of characters allowed in the textarea.
         */
        "maxLength"?: number;
        /**
          * The name of the textarea.
         */
        "name"?: string;
        /**
          * Emitted when the textarea loses focus.
         */
        "onBlur"?: (event: ModusWcTextareaCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the textarea value changes.
         */
        "onChange"?: (event: ModusWcTextareaCustomEvent<Event>) => void;
        /**
          * Emitted when the textarea gains focus.
         */
        "onFocus"?: (event: ModusWcTextareaCustomEvent<FocusEvent>) => void;
        /**
          * The placeholder text for the textarea.
         */
        "placeholder"?: string;
        /**
          * The readonly state of the textarea.
         */
        "readonly"?: boolean;
        /**
          * The required state of the textarea.
         */
        "required"?: boolean;
        /**
          * The number of visible text lines for the textarea.
         */
        "rows"?: number;
        /**
          * The tabindex of the textarea.
         */
        "tabIndex"?: number;
        /**
          * The value of the textarea.
         */
        "value"?: string;
    }
    /**
     * A customizable typography component used to render text with different sizes, variants, weights, and text casing.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTypography {
        /**
          * The aria-label for the typography component.
         */
        "ariaLabel": string;
        /**
          * The size option when variant "body" is selected.
         */
        "bodySize"?: TypographyBodySize;
        /**
          * Custom CSS class to apply to the typography element.
         */
        "customClass"?: string;
        /**
          * The text case.
         */
        "textCase"?: 'sentence' | 'title' | 'uppercase';
        /**
          * The variant of the typography component.
         */
        "variant"?: TypographyVariant;
        /**
          * The weight of the text.
         */
        "weight"?: 'regular' | 'semibold' | 'bold';
    }
    /**
     * A component used to render auto-generated Stencil documentation in Storybook stories.
     * Searches for the component directory within `/atoms`, `/molecules`, and `organisms`. Renders the `readme.md` file.
     */
    interface StencilDocs {
        /**
          * The component name used to find the proper directory.
         */
        "componentName": string;
    }
    interface IntrinsicElements {
        "modus-wc-avatar": ModusWcAvatar;
        "modus-wc-badge": ModusWcBadge;
        "modus-wc-button": ModusWcButton;
        "modus-wc-divider": ModusWcDivider;
        "modus-wc-text-input": ModusWcTextInput;
        "modus-wc-textarea": ModusWcTextarea;
        "modus-wc-typography": ModusWcTypography;
        "stencil-docs": StencilDocs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A customizable avatar component used to create avatars with different images.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-avatar": LocalJSX.ModusWcAvatar & JSXBase.HTMLAttributes<HTMLModusWcAvatarElement>;
            /**
             * A customizable badge component used to create badges with different sizes, types, and colors.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-badge": LocalJSX.ModusWcBadge & JSXBase.HTMLAttributes<HTMLModusWcBadgeElement>;
            /**
             * A customizable button component used to create buttons with different sizes, variants, and types.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-button": LocalJSX.ModusWcButton & JSXBase.HTMLAttributes<HTMLModusWcButtonElement>;
            /**
             * A customizable divider component used to separate content horizontally or vertically.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-divider": LocalJSX.ModusWcDivider & JSXBase.HTMLAttributes<HTMLModusWcDividerElement>;
            /**
             * A customizable input component used to create text inputs with types.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-text-input": LocalJSX.ModusWcTextInput & JSXBase.HTMLAttributes<HTMLModusWcTextInputElement>;
            /**
             * A customizable textarea component.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-textarea": LocalJSX.ModusWcTextarea & JSXBase.HTMLAttributes<HTMLModusWcTextareaElement>;
            /**
             * A customizable typography component used to render text with different sizes, variants, weights, and text casing.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-typography": LocalJSX.ModusWcTypography & JSXBase.HTMLAttributes<HTMLModusWcTypographyElement>;
            /**
             * A component used to render auto-generated Stencil documentation in Storybook stories.
             * Searches for the component directory within `/atoms`, `/molecules`, and `organisms`. Renders the `readme.md` file.
             */
            "stencil-docs": LocalJSX.StencilDocs & JSXBase.HTMLAttributes<HTMLStencilDocsElement>;
        }
    }
}
