/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Size } from "./components/types";
import { SpinnerColor, SpinnerVariant } from "./components/atoms/modus-wc-spinner/modus-wc-spinner";
import { IThemeConfig } from "./providers/theme/theme.types";
import { TypographyVariant, TypographyWeight } from "./components/atoms/modus-wc-typography/modus-wc-typography";
export { Size } from "./components/types";
export { SpinnerColor, SpinnerVariant } from "./components/atoms/modus-wc-spinner/modus-wc-spinner";
export { IThemeConfig } from "./providers/theme/theme.types";
export { TypographyVariant, TypographyWeight } from "./components/atoms/modus-wc-typography/modus-wc-typography";
export namespace Components {
    /**
     * A customizable avatar component used to create avatars with different images.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcAvatar {
        /**
          * The image alt attribute for accessibility.
         */
        "alt": string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass": string;
        /**
          * The location of the image.
         */
        "imgSrc": string;
        /**
          * The shape of the avatar.
         */
        "shape"?: 'circle' | 'square';
        /**
          * The size of the avatar.
         */
        "size"?: Size;
    }
    /**
     * A customizable badge component used to create badges with different sizes, types, and colors.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcBadge {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the badge.
         */
        "color": | 'primary'
    | 'secondary'
    | 'tertiary'
    | 'high-contrast'
    | 'success'
    | 'warning'
    | 'danger';
        /**
          * The content to display inside the badge. For 'counter' type, this should be a number.
         */
        "content": string;
        /**
          * Custom CSS class to apply to the span element.
         */
        "customClass": string;
        /**
          * The size of the badge.
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The variant of the badge.
         */
        "variant": 'counter' | 'filled' | 'text';
    }
    /**
     * A customizable button component used to create buttons with different sizes, variants, and types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcButton {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the button.
         */
        "color": 'primary' | 'secondary' | 'tertiary' | 'warning' | 'danger';
        /**
          * Custom CSS class to apply to the button element.
         */
        "customClass": string;
        /**
          * If true, the button will be disabled.
         */
        "disabled"?: boolean;
        /**
          * If true, the button will take the full width of its container.
         */
        "fullWidth"?: boolean;
        /**
          * The text label displayed on the button.
         */
        "label": string;
        /**
          * If true, the button will be in a pressed state (for toggle buttons).
         */
        "pressed"?: boolean;
        /**
          * The size of the button.
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The type of the button.
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * The variant of the button.
         */
        "variant": 'filled' | 'outlined' | 'text';
    }
    /**
     * A customizable checkbox component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcCheckbox {
        /**
          * The ID of the element that describes the checkbox.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The aria-labelledby attribute for usage with a label.
         */
        "ariaLabelledby"?: string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass": string;
        /**
          * The disabled state of the checkbox.
         */
        "disabled"?: boolean;
        /**
          * The indeterminate state of the checkbox.
         */
        "indeterminate": boolean;
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * The tabindex of the input.
         */
        "inputTabIndex"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: Size;
        /**
          * The value of the checkbox.
         */
        "value": boolean;
    }
    /**
     * A customizable date picker component used to create date inputs.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcDate {
        /**
          * The ID of the element that describes the input.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The aria-labelledby attribute for usage with a label.
         */
        "ariaLabelledby"?: string;
        /**
          * Indicates that an element should be focused on page load.
         */
        "autoFocus"?: boolean;
        /**
          * Indicates that the input should have a border.
         */
        "bordered"?: boolean;
        /**
          * Custom CSS class to apply to the input.
         */
        "customClass"?: string;
        /**
          * Whether the form control is disabled.
         */
        "disabled"?: boolean;
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * Determine the control's relative ordering for sequential focus navigation (typically with the Tab key).
         */
        "inputTabIndex"?: number;
        /**
          * Maximum date value.
         */
        "max"?: string;
        /**
          * Minimum date value.
         */
        "min"?: string;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * Placeholder text for the date input.
         */
        "placeholder"?: string;
        /**
          * Whether the value is editable.
         */
        "readOnly"?: boolean;
        /**
          * A value is required or must be checked for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The value of the control.
         */
        "value": string;
    }
    /**
     * A customizable divider component used to separate content horizontally or vertically.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcDivider {
        /**
          * The aria-label attribute used for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color of the divider line.
         */
        "color"?: | 'primary'
    | 'secondary'
    | 'tertiary'
    | 'high-contrast'
    | 'success'
    | 'warning'
    | 'danger';
        /**
          * The content to display in the divider.
         */
        "content"?: string;
        /**
          * Custom CSS class to apply to the divider element.
         */
        "customClass": string;
        /**
          * The orientation of the divider. This is in reference to how content will be rendered around the divider.
         */
        "orientation"?: 'horizontal' | 'vertical';
        /**
          * The position of the divider.
         */
        "position"?: 'center' | 'end' | 'start';
        /**
          * Whether the divider is responsive or not.
         */
        "responsive"?: boolean;
    }
    /**
     * A customizable icon component used to render Modus icons.
     * <b>This component requires Modus icons to be installed in the host application. See [Modus Icon Usage](/docs/documentation-modus-icon-usage--docs) for steps.</b>
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcIcon {
        /**
          * The aria-label attribute for accessibility. This provides an accessible name for screen readers.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the i element.
         */
        "customClass": string;
        /**
          * Indicates that the icon is decorative. When true, sets aria-hidden to hide the icon from screen readers.
         */
        "decorative"?: boolean;
        /**
          * The icon name, should match the CSS class in the icon font.
         */
        "name": string;
        /**
          * The icon size, can be "sm", "md", "lg" (a custom size can be specified in CSS). This adjusts the font size for the icon.
         */
        "size"?: Size;
    }
    /**
     * A customizable input label component.
     * The component supports a `<slot>` for injecting additional custom content inside the label, such as icons or formatted text.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcInputLabel {
        /**
          * Additional classes for custom styling.
         */
        "customClass"?: string;
        /**
          * The `for` attribute of the label, matching the `id` of the associated input.
         */
        "forId"?: string;
        /**
          * Specifies the text direction of the label content.
         */
        "labelDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The text to display within the label.
         */
        "labelText"?: string;
        /**
          * Whether the label indicates a required field.
         */
        "required"?: boolean;
    }
    /**
     * A customizable input component used to create number inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcNumberInput {
        /**
          * The ID of the element that describes the input.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Hint for form autofill feature.
         */
        "autoComplete"?: 'on' | 'off';
        /**
          * Indicates that an element should be focused on page load.
         */
        "autoFocus"?: boolean;
        /**
          * Indicates that the input should have a border.
         */
        "bordered"?: boolean;
        /**
          * Custom CSS class to apply to the input.
         */
        "customClass"?: string;
        /**
          * Whether the form control is disabled.
         */
        "disabled"?: boolean;
        /**
          * Indicates whether the input has an invalid input.
         */
        "inputAriaInvalid"?: 'true' | 'false';
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * Hints at the type of data that might be entered by the user while editing the element or its contents. This allows a browser to display an appropriate virtual keyboard.
         */
        "inputMode": 'decimal' | 'none' | 'numeric';
        /**
          * Determine the control's relative ordering for sequential focus navigation (typically with the Tab key).
         */
        "inputTabIndex"?: number;
        /**
          * The input's maximum value.
         */
        "max"?: number;
        /**
          * The input's minimum value.
         */
        "min"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * Text that appears in the form control when it has no value set.
         */
        "placeholder"?: string;
        /**
          * Whether the value is editable.
         */
        "readOnly"?: boolean;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The granularity that the value adheres to.
         */
        "step"?: number;
        /**
          * Type of form control.
         */
        "type"?: 'number' | 'range';
        /**
          * The value of the control.
         */
        "value": string;
    }
    /**
     * A customizable radio component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcRadio {
        /**
          * The ID of the element that describes the radio.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The aria-labelledby attribute for usage with a label.
         */
        "ariaLabelledby"?: string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass": string;
        /**
          * The disabled state of the radio.
         */
        "disabled"?: boolean;
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * The tabindex of the input.
         */
        "inputTabIndex"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The value of the radio.
         */
        "value": boolean;
    }
    /**
     * A customizable skeleton component used to create skeletons of various sizes and shapes.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcSkeleton {
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass": string;
        /**
          * The height of the skeleton.
         */
        "height": string;
        /**
          * The shape of the skeleton.
         */
        "shape"?: 'circle' | 'rectangle';
        /**
          * The width of the skeleton.
         */
        "width": string;
    }
    /**
     * A customizable slider component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcSlider {
        /**
          * The ID of the element that describes the slider.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The aria-labelledby attribute for usage with a label.
         */
        "ariaLabelledby"?: string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass": string;
        /**
          * The disabled state of the slider.
         */
        "disabled"?: boolean;
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * The tabindex of the input.
         */
        "inputTabIndex"?: number;
        /**
          * The maximum slider value.
         */
        "max"?: number;
        /**
          * The minimum slider value.
         */
        "min"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: Size;
        /**
          * The increment of the slider.
         */
        "step"?: number;
        /**
          * The value of the slider.
         */
        "value": number;
    }
    /**
     * A customizable spinner component used to indicate the loading of content.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcSpinner {
        /**
          * The aria-label attribute used for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color of the spinner.
         */
        "color": SpinnerColor;
        /**
          * Custom CSS class to apply to the spinner element.
         */
        "customClass": string;
        /**
          * The size of the spinner.
         */
        "size": Size;
        /**
          * The variant of the spinner.
         */
        "variant": SpinnerVariant;
    }
    /**
     * A customizable input component used to create text inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTextInput {
        /**
          * The ID of the element that describes the input.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Controls automatic capitalization in inputted text.
         */
        "autoCapitalize"?: | 'off'
    | 'none'
    | 'on'
    | 'sentences'
    | 'words'
    | 'characters';
        /**
          * Hint for form autofill feature.
         */
        "autoComplete"?: 'on' | 'off';
        /**
          * Indicates that an element should be focused on page load.
         */
        "autoFocus"?: boolean;
        /**
          * Indicates that the input should have a border.
         */
        "bordered"?: boolean;
        /**
          * Custom CSS class to apply to the input.
         */
        "customClass"?: string;
        /**
          * Whether the form control is disabled.
         */
        "disabled"?: boolean;
        /**
          * Indicates whether the input has an invalid input.
         */
        "inputAriaInvalid"?: 'grammar' | 'spelling' | 'true' | 'false';
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * Hints at the type of data that might be entered by the user while editing the element or its contents. This allows a browser to display an appropriate virtual keyboard.
         */
        "inputMode": | 'decimal'
    | 'email'
    | 'none'
    | 'numeric'
    | 'search'
    | 'tel'
    | 'text'
    | 'url';
        /**
          * Whether the element may be checked for spelling errors. A hint for the browser, not a guarantee.
         */
        "inputSpellcheck"?: boolean;
        /**
          * Determine the control's relative ordering for sequential focus navigation (typically with the Tab key).
         */
        "inputTabIndex"?: number;
        /**
          * Maximum length (number of characters) of value.
         */
        "maxLength"?: number;
        /**
          * Minimum length (number of characters) of value.
         */
        "minLength"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * Pattern the value must match to be valid
         */
        "pattern"?: string;
        /**
          * Text that appears in the form control when it has no value set.
         */
        "placeholder"?: string;
        /**
          * Whether the value is editable.
         */
        "readOnly"?: boolean;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: Size;
        /**
          * Type of form control.
         */
        "type"?: 'email' | 'password' | 'search' | 'tel' | 'text' | 'url';
        /**
          * The value of the control.
         */
        "value": string;
    }
    /**
     * A customizable textarea component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTextarea {
        /**
          * The ID of the element that describes the textarea.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Indicates that the input should have a border.
         */
        "bordered"?: boolean;
        /**
          * Custom CSS class to apply to the textarea (supports DaisyUI).
         */
        "customClass"?: string;
        /**
          * The disabled state of the textarea.
         */
        "disabled"?: boolean;
        /**
          * Indicates whether the input is invalid.
         */
        "inputAriaInvalid"?: 'grammar' | 'spelling' | 'true' | 'false';
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * Whether the element may be checked for spelling errors. A hint for the browser, not a guarantee.
         */
        "inputSpellcheck"?: boolean;
        /**
          * The tabindex of the input.
         */
        "inputTabIndex"?: number;
        /**
          * The maximum number of characters allowed in the textarea.
         */
        "maxLength"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * The placeholder text for the textarea.
         */
        "placeholder"?: string;
        /**
          * The readonly state of the textarea.
         */
        "readonly"?: boolean;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The number of visible text lines for the textarea.
         */
        "rows"?: number;
        /**
          * The size of the input.
         */
        "size"?: Size;
        /**
          * The value of the textarea.
         */
        "value": string;
    }
    interface ModusWcThemeProvider {
        "initialTheme"?: Partial<IThemeConfig>;
    }
    /**
     * A theme switcher component used to toggle the application theme and/or mode.
     * Allows consumers to set the initial theme (Modus Classic, Prism, etc) and end-users to toggle modes (Light, Dark).
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcThemeSwitcher {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the theme switcher element.
         */
        "customClass": string;
    }
    /**
     * A customizable checkbox component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcToggle {
        /**
          * The ID of the element that describes the toggle.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The aria-labelledby attribute for usage with a label.
         */
        "ariaLabelledby"?: string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass": string;
        /**
          * The disabled state of the toggle.
         */
        "disabled"?: boolean;
        /**
          * The indeterminate state of the toggle.
         */
        "indeterminate": boolean;
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * The tabindex of the input.
         */
        "inputTabIndex"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: Size;
        /**
          * The value of the toggle.
         */
        "value": boolean;
    }
    /**
     * A customizable tooltip component used to create tooltips with different content.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTooltip {
        /**
          * The text content of the tooltip.
         */
        "content": string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass": string;
        /**
          * Use this attribute to force the tooltip to remain open.
         */
        "forceOpen"?: boolean;
        /**
          * The position that the tooltip will render in relation to the element.
         */
        "position"?: 'auto' | 'top' | 'right' | 'bottom' | 'left';
        /**
          * The ID of the tooltip element, useful for setting the "aria-describedby" attribute of related elements.
         */
        "tooltipId"?: string;
    }
    /**
     * A customizable typography component used to render text with different sizes, variants, and weights.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTypography {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the typography element.
         */
        "customClass"?: string;
        /**
          * The size of the font.
         */
        "size"?: Size;
        /**
          * The variant of the typography component.
         */
        "variant": TypographyVariant;
        /**
          * The weight of the text.
         */
        "weight"?: TypographyWeight;
    }
}
export interface ModusWcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcButtonElement;
}
export interface ModusWcCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcCheckboxElement;
}
export interface ModusWcDateCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcDateElement;
}
export interface ModusWcNumberInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcNumberInputElement;
}
export interface ModusWcRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcRadioElement;
}
export interface ModusWcSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcSliderElement;
}
export interface ModusWcTextInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcTextInputElement;
}
export interface ModusWcTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcTextareaElement;
}
export interface ModusWcThemeSwitcherCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcThemeSwitcherElement;
}
export interface ModusWcToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusWcToggleElement;
}
declare global {
    /**
     * A customizable avatar component used to create avatars with different images.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcAvatarElement extends Components.ModusWcAvatar, HTMLStencilElement {
    }
    var HTMLModusWcAvatarElement: {
        prototype: HTMLModusWcAvatarElement;
        new (): HTMLModusWcAvatarElement;
    };
    /**
     * A customizable badge component used to create badges with different sizes, types, and colors.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcBadgeElement extends Components.ModusWcBadge, HTMLStencilElement {
    }
    var HTMLModusWcBadgeElement: {
        prototype: HTMLModusWcBadgeElement;
        new (): HTMLModusWcBadgeElement;
    };
    interface HTMLModusWcButtonElementEventMap {
        "buttonClick": MouseEvent | KeyboardEvent;
    }
    /**
     * A customizable button component used to create buttons with different sizes, variants, and types.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcButtonElement extends Components.ModusWcButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcButtonElementEventMap>(type: K, listener: (this: HTMLModusWcButtonElement, ev: ModusWcButtonCustomEvent<HTMLModusWcButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcButtonElementEventMap>(type: K, listener: (this: HTMLModusWcButtonElement, ev: ModusWcButtonCustomEvent<HTMLModusWcButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcButtonElement: {
        prototype: HTMLModusWcButtonElement;
        new (): HTMLModusWcButtonElement;
    };
    interface HTMLModusWcCheckboxElementEventMap {
        "inputBlur": FocusEvent;
        "inputChange": Event;
        "inputFocus": FocusEvent;
    }
    /**
     * A customizable checkbox component.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcCheckboxElement extends Components.ModusWcCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcCheckboxElementEventMap>(type: K, listener: (this: HTMLModusWcCheckboxElement, ev: ModusWcCheckboxCustomEvent<HTMLModusWcCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcCheckboxElementEventMap>(type: K, listener: (this: HTMLModusWcCheckboxElement, ev: ModusWcCheckboxCustomEvent<HTMLModusWcCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcCheckboxElement: {
        prototype: HTMLModusWcCheckboxElement;
        new (): HTMLModusWcCheckboxElement;
    };
    interface HTMLModusWcDateElementEventMap {
        "inputBlur": FocusEvent;
        "inputChange": Event;
        "inputFocus": FocusEvent;
    }
    /**
     * A customizable date picker component used to create date inputs.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcDateElement extends Components.ModusWcDate, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcDateElementEventMap>(type: K, listener: (this: HTMLModusWcDateElement, ev: ModusWcDateCustomEvent<HTMLModusWcDateElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcDateElementEventMap>(type: K, listener: (this: HTMLModusWcDateElement, ev: ModusWcDateCustomEvent<HTMLModusWcDateElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcDateElement: {
        prototype: HTMLModusWcDateElement;
        new (): HTMLModusWcDateElement;
    };
    /**
     * A customizable divider component used to separate content horizontally or vertically.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcDividerElement extends Components.ModusWcDivider, HTMLStencilElement {
    }
    var HTMLModusWcDividerElement: {
        prototype: HTMLModusWcDividerElement;
        new (): HTMLModusWcDividerElement;
    };
    /**
     * A customizable icon component used to render Modus icons.
     * <b>This component requires Modus icons to be installed in the host application. See [Modus Icon Usage](/docs/documentation-modus-icon-usage--docs) for steps.</b>
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcIconElement extends Components.ModusWcIcon, HTMLStencilElement {
    }
    var HTMLModusWcIconElement: {
        prototype: HTMLModusWcIconElement;
        new (): HTMLModusWcIconElement;
    };
    /**
     * A customizable input label component.
     * The component supports a `<slot>` for injecting additional custom content inside the label, such as icons or formatted text.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcInputLabelElement extends Components.ModusWcInputLabel, HTMLStencilElement {
    }
    var HTMLModusWcInputLabelElement: {
        prototype: HTMLModusWcInputLabelElement;
        new (): HTMLModusWcInputLabelElement;
    };
    interface HTMLModusWcNumberInputElementEventMap {
        "inputBlur": FocusEvent;
        "inputChange": Event;
        "inputFocus": FocusEvent;
    }
    /**
     * A customizable input component used to create number inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcNumberInputElement extends Components.ModusWcNumberInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcNumberInputElementEventMap>(type: K, listener: (this: HTMLModusWcNumberInputElement, ev: ModusWcNumberInputCustomEvent<HTMLModusWcNumberInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcNumberInputElementEventMap>(type: K, listener: (this: HTMLModusWcNumberInputElement, ev: ModusWcNumberInputCustomEvent<HTMLModusWcNumberInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcNumberInputElement: {
        prototype: HTMLModusWcNumberInputElement;
        new (): HTMLModusWcNumberInputElement;
    };
    interface HTMLModusWcRadioElementEventMap {
        "inputBlur": FocusEvent;
        "inputChange": Event;
        "inputFocus": FocusEvent;
    }
    /**
     * A customizable radio component.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcRadioElement extends Components.ModusWcRadio, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcRadioElementEventMap>(type: K, listener: (this: HTMLModusWcRadioElement, ev: ModusWcRadioCustomEvent<HTMLModusWcRadioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcRadioElementEventMap>(type: K, listener: (this: HTMLModusWcRadioElement, ev: ModusWcRadioCustomEvent<HTMLModusWcRadioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcRadioElement: {
        prototype: HTMLModusWcRadioElement;
        new (): HTMLModusWcRadioElement;
    };
    /**
     * A customizable skeleton component used to create skeletons of various sizes and shapes.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcSkeletonElement extends Components.ModusWcSkeleton, HTMLStencilElement {
    }
    var HTMLModusWcSkeletonElement: {
        prototype: HTMLModusWcSkeletonElement;
        new (): HTMLModusWcSkeletonElement;
    };
    interface HTMLModusWcSliderElementEventMap {
        "inputBlur": FocusEvent;
        "inputChange": Event;
        "inputFocus": FocusEvent;
    }
    /**
     * A customizable slider component.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcSliderElement extends Components.ModusWcSlider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcSliderElementEventMap>(type: K, listener: (this: HTMLModusWcSliderElement, ev: ModusWcSliderCustomEvent<HTMLModusWcSliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcSliderElementEventMap>(type: K, listener: (this: HTMLModusWcSliderElement, ev: ModusWcSliderCustomEvent<HTMLModusWcSliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcSliderElement: {
        prototype: HTMLModusWcSliderElement;
        new (): HTMLModusWcSliderElement;
    };
    /**
     * A customizable spinner component used to indicate the loading of content.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcSpinnerElement extends Components.ModusWcSpinner, HTMLStencilElement {
    }
    var HTMLModusWcSpinnerElement: {
        prototype: HTMLModusWcSpinnerElement;
        new (): HTMLModusWcSpinnerElement;
    };
    interface HTMLModusWcTextInputElementEventMap {
        "inputBlur": FocusEvent;
        "inputChange": Event;
        "inputFocus": FocusEvent;
    }
    /**
     * A customizable input component used to create text inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcTextInputElement extends Components.ModusWcTextInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcTextInputElementEventMap>(type: K, listener: (this: HTMLModusWcTextInputElement, ev: ModusWcTextInputCustomEvent<HTMLModusWcTextInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcTextInputElementEventMap>(type: K, listener: (this: HTMLModusWcTextInputElement, ev: ModusWcTextInputCustomEvent<HTMLModusWcTextInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcTextInputElement: {
        prototype: HTMLModusWcTextInputElement;
        new (): HTMLModusWcTextInputElement;
    };
    interface HTMLModusWcTextareaElementEventMap {
        "inputBlur": FocusEvent;
        "inputChange": Event;
        "inputFocus": FocusEvent;
    }
    /**
     * A customizable textarea component.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcTextareaElement extends Components.ModusWcTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcTextareaElementEventMap>(type: K, listener: (this: HTMLModusWcTextareaElement, ev: ModusWcTextareaCustomEvent<HTMLModusWcTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcTextareaElementEventMap>(type: K, listener: (this: HTMLModusWcTextareaElement, ev: ModusWcTextareaCustomEvent<HTMLModusWcTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcTextareaElement: {
        prototype: HTMLModusWcTextareaElement;
        new (): HTMLModusWcTextareaElement;
    };
    interface HTMLModusWcThemeProviderElement extends Components.ModusWcThemeProvider, HTMLStencilElement {
    }
    var HTMLModusWcThemeProviderElement: {
        prototype: HTMLModusWcThemeProviderElement;
        new (): HTMLModusWcThemeProviderElement;
    };
    interface HTMLModusWcThemeSwitcherElementEventMap {
        "themeChange": IThemeConfig;
    }
    /**
     * A theme switcher component used to toggle the application theme and/or mode.
     * Allows consumers to set the initial theme (Modus Classic, Prism, etc) and end-users to toggle modes (Light, Dark).
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcThemeSwitcherElement extends Components.ModusWcThemeSwitcher, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcThemeSwitcherElementEventMap>(type: K, listener: (this: HTMLModusWcThemeSwitcherElement, ev: ModusWcThemeSwitcherCustomEvent<HTMLModusWcThemeSwitcherElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcThemeSwitcherElementEventMap>(type: K, listener: (this: HTMLModusWcThemeSwitcherElement, ev: ModusWcThemeSwitcherCustomEvent<HTMLModusWcThemeSwitcherElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcThemeSwitcherElement: {
        prototype: HTMLModusWcThemeSwitcherElement;
        new (): HTMLModusWcThemeSwitcherElement;
    };
    interface HTMLModusWcToggleElementEventMap {
        "inputBlur": FocusEvent;
        "inputChange": Event;
        "inputFocus": FocusEvent;
    }
    /**
     * A customizable checkbox component.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcToggleElement extends Components.ModusWcToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModusWcToggleElementEventMap>(type: K, listener: (this: HTMLModusWcToggleElement, ev: ModusWcToggleCustomEvent<HTMLModusWcToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModusWcToggleElementEventMap>(type: K, listener: (this: HTMLModusWcToggleElement, ev: ModusWcToggleCustomEvent<HTMLModusWcToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModusWcToggleElement: {
        prototype: HTMLModusWcToggleElement;
        new (): HTMLModusWcToggleElement;
    };
    /**
     * A customizable tooltip component used to create tooltips with different content.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcTooltipElement extends Components.ModusWcTooltip, HTMLStencilElement {
    }
    var HTMLModusWcTooltipElement: {
        prototype: HTMLModusWcTooltipElement;
        new (): HTMLModusWcTooltipElement;
    };
    /**
     * A customizable typography component used to render text with different sizes, variants, and weights.
     * Adheres to WCAG 2.2 standards.
     */
    interface HTMLModusWcTypographyElement extends Components.ModusWcTypography, HTMLStencilElement {
    }
    var HTMLModusWcTypographyElement: {
        prototype: HTMLModusWcTypographyElement;
        new (): HTMLModusWcTypographyElement;
    };
    interface HTMLElementTagNameMap {
        "modus-wc-avatar": HTMLModusWcAvatarElement;
        "modus-wc-badge": HTMLModusWcBadgeElement;
        "modus-wc-button": HTMLModusWcButtonElement;
        "modus-wc-checkbox": HTMLModusWcCheckboxElement;
        "modus-wc-date": HTMLModusWcDateElement;
        "modus-wc-divider": HTMLModusWcDividerElement;
        "modus-wc-icon": HTMLModusWcIconElement;
        "modus-wc-input-label": HTMLModusWcInputLabelElement;
        "modus-wc-number-input": HTMLModusWcNumberInputElement;
        "modus-wc-radio": HTMLModusWcRadioElement;
        "modus-wc-skeleton": HTMLModusWcSkeletonElement;
        "modus-wc-slider": HTMLModusWcSliderElement;
        "modus-wc-spinner": HTMLModusWcSpinnerElement;
        "modus-wc-text-input": HTMLModusWcTextInputElement;
        "modus-wc-textarea": HTMLModusWcTextareaElement;
        "modus-wc-theme-provider": HTMLModusWcThemeProviderElement;
        "modus-wc-theme-switcher": HTMLModusWcThemeSwitcherElement;
        "modus-wc-toggle": HTMLModusWcToggleElement;
        "modus-wc-tooltip": HTMLModusWcTooltipElement;
        "modus-wc-typography": HTMLModusWcTypographyElement;
    }
}
declare namespace LocalJSX {
    /**
     * A customizable avatar component used to create avatars with different images.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcAvatar {
        /**
          * The image alt attribute for accessibility.
         */
        "alt": string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass"?: string;
        /**
          * The location of the image.
         */
        "imgSrc"?: string;
        /**
          * The shape of the avatar.
         */
        "shape"?: 'circle' | 'square';
        /**
          * The size of the avatar.
         */
        "size"?: Size;
    }
    /**
     * A customizable badge component used to create badges with different sizes, types, and colors.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcBadge {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the badge.
         */
        "color"?: | 'primary'
    | 'secondary'
    | 'tertiary'
    | 'high-contrast'
    | 'success'
    | 'warning'
    | 'danger';
        /**
          * The content to display inside the badge. For 'counter' type, this should be a number.
         */
        "content": string;
        /**
          * Custom CSS class to apply to the span element.
         */
        "customClass"?: string;
        /**
          * The size of the badge.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The variant of the badge.
         */
        "variant"?: 'counter' | 'filled' | 'text';
    }
    /**
     * A customizable button component used to create buttons with different sizes, variants, and types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcButton {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color variant of the button.
         */
        "color"?: 'primary' | 'secondary' | 'tertiary' | 'warning' | 'danger';
        /**
          * Custom CSS class to apply to the button element.
         */
        "customClass"?: string;
        /**
          * If true, the button will be disabled.
         */
        "disabled"?: boolean;
        /**
          * If true, the button will take the full width of its container.
         */
        "fullWidth"?: boolean;
        /**
          * The text label displayed on the button.
         */
        "label": string;
        /**
          * Event emitted when the button is clicked or activated via keyboard.
         */
        "onButtonClick"?: (event: ModusWcButtonCustomEvent<MouseEvent | KeyboardEvent>) => void;
        /**
          * If true, the button will be in a pressed state (for toggle buttons).
         */
        "pressed"?: boolean;
        /**
          * The size of the button.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The type of the button.
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * The variant of the button.
         */
        "variant"?: 'filled' | 'outlined' | 'text';
    }
    /**
     * A customizable checkbox component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcCheckbox {
        /**
          * The ID of the element that describes the checkbox.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The aria-labelledby attribute for usage with a label.
         */
        "ariaLabelledby"?: string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass"?: string;
        /**
          * The disabled state of the checkbox.
         */
        "disabled"?: boolean;
        /**
          * The indeterminate state of the checkbox.
         */
        "indeterminate"?: boolean;
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * The tabindex of the input.
         */
        "inputTabIndex"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus.
         */
        "onInputBlur"?: (event: ModusWcCheckboxCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the input value changes.
         */
        "onInputChange"?: (event: ModusWcCheckboxCustomEvent<Event>) => void;
        /**
          * Emitted when the input gains focus.
         */
        "onInputFocus"?: (event: ModusWcCheckboxCustomEvent<FocusEvent>) => void;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: Size;
        /**
          * The value of the checkbox.
         */
        "value"?: boolean;
    }
    /**
     * A customizable date picker component used to create date inputs.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcDate {
        /**
          * The ID of the element that describes the input.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The aria-labelledby attribute for usage with a label.
         */
        "ariaLabelledby"?: string;
        /**
          * Indicates that an element should be focused on page load.
         */
        "autoFocus"?: boolean;
        /**
          * Indicates that the input should have a border.
         */
        "bordered"?: boolean;
        /**
          * Custom CSS class to apply to the input.
         */
        "customClass"?: string;
        /**
          * Whether the form control is disabled.
         */
        "disabled"?: boolean;
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * Determine the control's relative ordering for sequential focus navigation (typically with the Tab key).
         */
        "inputTabIndex"?: number;
        /**
          * Maximum date value.
         */
        "max"?: string;
        /**
          * Minimum date value.
         */
        "min"?: string;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * Event emitted when the input loses focus.
         */
        "onInputBlur"?: (event: ModusWcDateCustomEvent<FocusEvent>) => void;
        /**
          * Event emitted when the input value changes.
         */
        "onInputChange"?: (event: ModusWcDateCustomEvent<Event>) => void;
        /**
          * Event emitted when the input gains focus.
         */
        "onInputFocus"?: (event: ModusWcDateCustomEvent<FocusEvent>) => void;
        /**
          * Placeholder text for the date input.
         */
        "placeholder"?: string;
        /**
          * Whether the value is editable.
         */
        "readOnly"?: boolean;
        /**
          * A value is required or must be checked for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The value of the control.
         */
        "value"?: string;
    }
    /**
     * A customizable divider component used to separate content horizontally or vertically.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcDivider {
        /**
          * The aria-label attribute used for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color of the divider line.
         */
        "color"?: | 'primary'
    | 'secondary'
    | 'tertiary'
    | 'high-contrast'
    | 'success'
    | 'warning'
    | 'danger';
        /**
          * The content to display in the divider.
         */
        "content"?: string;
        /**
          * Custom CSS class to apply to the divider element.
         */
        "customClass"?: string;
        /**
          * The orientation of the divider. This is in reference to how content will be rendered around the divider.
         */
        "orientation"?: 'horizontal' | 'vertical';
        /**
          * The position of the divider.
         */
        "position"?: 'center' | 'end' | 'start';
        /**
          * Whether the divider is responsive or not.
         */
        "responsive"?: boolean;
    }
    /**
     * A customizable icon component used to render Modus icons.
     * <b>This component requires Modus icons to be installed in the host application. See [Modus Icon Usage](/docs/documentation-modus-icon-usage--docs) for steps.</b>
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcIcon {
        /**
          * The aria-label attribute for accessibility. This provides an accessible name for screen readers.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the i element.
         */
        "customClass"?: string;
        /**
          * Indicates that the icon is decorative. When true, sets aria-hidden to hide the icon from screen readers.
         */
        "decorative"?: boolean;
        /**
          * The icon name, should match the CSS class in the icon font.
         */
        "name": string;
        /**
          * The icon size, can be "sm", "md", "lg" (a custom size can be specified in CSS). This adjusts the font size for the icon.
         */
        "size"?: Size;
    }
    /**
     * A customizable input label component.
     * The component supports a `<slot>` for injecting additional custom content inside the label, such as icons or formatted text.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcInputLabel {
        /**
          * Additional classes for custom styling.
         */
        "customClass"?: string;
        /**
          * The `for` attribute of the label, matching the `id` of the associated input.
         */
        "forId"?: string;
        /**
          * Specifies the text direction of the label content.
         */
        "labelDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The text to display within the label.
         */
        "labelText"?: string;
        /**
          * Whether the label indicates a required field.
         */
        "required"?: boolean;
    }
    /**
     * A customizable input component used to create number inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcNumberInput {
        /**
          * The ID of the element that describes the input.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Hint for form autofill feature.
         */
        "autoComplete"?: 'on' | 'off';
        /**
          * Indicates that an element should be focused on page load.
         */
        "autoFocus"?: boolean;
        /**
          * Indicates that the input should have a border.
         */
        "bordered"?: boolean;
        /**
          * Custom CSS class to apply to the input.
         */
        "customClass"?: string;
        /**
          * Whether the form control is disabled.
         */
        "disabled"?: boolean;
        /**
          * Indicates whether the input has an invalid input.
         */
        "inputAriaInvalid"?: 'true' | 'false';
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * Hints at the type of data that might be entered by the user while editing the element or its contents. This allows a browser to display an appropriate virtual keyboard.
         */
        "inputMode"?: 'decimal' | 'none' | 'numeric';
        /**
          * Determine the control's relative ordering for sequential focus navigation (typically with the Tab key).
         */
        "inputTabIndex"?: number;
        /**
          * The input's maximum value.
         */
        "max"?: number;
        /**
          * The input's minimum value.
         */
        "min"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * Event emitted when the input loses focus.
         */
        "onInputBlur"?: (event: ModusWcNumberInputCustomEvent<FocusEvent>) => void;
        /**
          * Event emitted when the input value changes.
         */
        "onInputChange"?: (event: ModusWcNumberInputCustomEvent<Event>) => void;
        /**
          * Event emitted when the input gains focus.
         */
        "onInputFocus"?: (event: ModusWcNumberInputCustomEvent<FocusEvent>) => void;
        /**
          * Text that appears in the form control when it has no value set.
         */
        "placeholder"?: string;
        /**
          * Whether the value is editable.
         */
        "readOnly"?: boolean;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The granularity that the value adheres to.
         */
        "step"?: number;
        /**
          * Type of form control.
         */
        "type"?: 'number' | 'range';
        /**
          * The value of the control.
         */
        "value"?: string;
    }
    /**
     * A customizable radio component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcRadio {
        /**
          * The ID of the element that describes the radio.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The aria-labelledby attribute for usage with a label.
         */
        "ariaLabelledby"?: string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass"?: string;
        /**
          * The disabled state of the radio.
         */
        "disabled"?: boolean;
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * The tabindex of the input.
         */
        "inputTabIndex"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus.
         */
        "onInputBlur"?: (event: ModusWcRadioCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the input value changes.
         */
        "onInputChange"?: (event: ModusWcRadioCustomEvent<Event>) => void;
        /**
          * Emitted when the input gains focus.
         */
        "onInputFocus"?: (event: ModusWcRadioCustomEvent<FocusEvent>) => void;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The value of the radio.
         */
        "value"?: boolean;
    }
    /**
     * A customizable skeleton component used to create skeletons of various sizes and shapes.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcSkeleton {
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass"?: string;
        /**
          * The height of the skeleton.
         */
        "height"?: string;
        /**
          * The shape of the skeleton.
         */
        "shape"?: 'circle' | 'rectangle';
        /**
          * The width of the skeleton.
         */
        "width"?: string;
    }
    /**
     * A customizable slider component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcSlider {
        /**
          * The ID of the element that describes the slider.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The aria-labelledby attribute for usage with a label.
         */
        "ariaLabelledby"?: string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass"?: string;
        /**
          * The disabled state of the slider.
         */
        "disabled"?: boolean;
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * The tabindex of the input.
         */
        "inputTabIndex"?: number;
        /**
          * The maximum slider value.
         */
        "max"?: number;
        /**
          * The minimum slider value.
         */
        "min"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus.
         */
        "onInputBlur"?: (event: ModusWcSliderCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the input value changes.
         */
        "onInputChange"?: (event: ModusWcSliderCustomEvent<Event>) => void;
        /**
          * Emitted when the input gains focus.
         */
        "onInputFocus"?: (event: ModusWcSliderCustomEvent<FocusEvent>) => void;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: Size;
        /**
          * The increment of the slider.
         */
        "step"?: number;
        /**
          * The value of the slider.
         */
        "value"?: number;
    }
    /**
     * A customizable spinner component used to indicate the loading of content.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcSpinner {
        /**
          * The aria-label attribute used for accessibility.
         */
        "ariaLabel": string;
        /**
          * The color of the spinner.
         */
        "color"?: SpinnerColor;
        /**
          * Custom CSS class to apply to the spinner element.
         */
        "customClass"?: string;
        /**
          * The size of the spinner.
         */
        "size"?: Size;
        /**
          * The variant of the spinner.
         */
        "variant"?: SpinnerVariant;
    }
    /**
     * A customizable input component used to create text inputs with types.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTextInput {
        /**
          * The ID of the element that describes the input.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Controls automatic capitalization in inputted text.
         */
        "autoCapitalize"?: | 'off'
    | 'none'
    | 'on'
    | 'sentences'
    | 'words'
    | 'characters';
        /**
          * Hint for form autofill feature.
         */
        "autoComplete"?: 'on' | 'off';
        /**
          * Indicates that an element should be focused on page load.
         */
        "autoFocus"?: boolean;
        /**
          * Indicates that the input should have a border.
         */
        "bordered"?: boolean;
        /**
          * Custom CSS class to apply to the input.
         */
        "customClass"?: string;
        /**
          * Whether the form control is disabled.
         */
        "disabled"?: boolean;
        /**
          * Indicates whether the input has an invalid input.
         */
        "inputAriaInvalid"?: 'grammar' | 'spelling' | 'true' | 'false';
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * Hints at the type of data that might be entered by the user while editing the element or its contents. This allows a browser to display an appropriate virtual keyboard.
         */
        "inputMode"?: | 'decimal'
    | 'email'
    | 'none'
    | 'numeric'
    | 'search'
    | 'tel'
    | 'text'
    | 'url';
        /**
          * Whether the element may be checked for spelling errors. A hint for the browser, not a guarantee.
         */
        "inputSpellcheck"?: boolean;
        /**
          * Determine the control's relative ordering for sequential focus navigation (typically with the Tab key).
         */
        "inputTabIndex"?: number;
        /**
          * Maximum length (number of characters) of value.
         */
        "maxLength"?: number;
        /**
          * Minimum length (number of characters) of value.
         */
        "minLength"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * Event emitted when the input loses focus.
         */
        "onInputBlur"?: (event: ModusWcTextInputCustomEvent<FocusEvent>) => void;
        /**
          * Event emitted when the input value changes.
         */
        "onInputChange"?: (event: ModusWcTextInputCustomEvent<Event>) => void;
        /**
          * Event emitted when the input gains focus.
         */
        "onInputFocus"?: (event: ModusWcTextInputCustomEvent<FocusEvent>) => void;
        /**
          * Pattern the value must match to be valid
         */
        "pattern"?: string;
        /**
          * Text that appears in the form control when it has no value set.
         */
        "placeholder"?: string;
        /**
          * Whether the value is editable.
         */
        "readOnly"?: boolean;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: Size;
        /**
          * Type of form control.
         */
        "type"?: 'email' | 'password' | 'search' | 'tel' | 'text' | 'url';
        /**
          * The value of the control.
         */
        "value"?: string;
    }
    /**
     * A customizable textarea component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTextarea {
        /**
          * The ID of the element that describes the textarea.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Indicates that the input should have a border.
         */
        "bordered"?: boolean;
        /**
          * Custom CSS class to apply to the textarea (supports DaisyUI).
         */
        "customClass"?: string;
        /**
          * The disabled state of the textarea.
         */
        "disabled"?: boolean;
        /**
          * Indicates whether the input is invalid.
         */
        "inputAriaInvalid"?: 'grammar' | 'spelling' | 'true' | 'false';
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * Whether the element may be checked for spelling errors. A hint for the browser, not a guarantee.
         */
        "inputSpellcheck"?: boolean;
        /**
          * The tabindex of the input.
         */
        "inputTabIndex"?: number;
        /**
          * The maximum number of characters allowed in the textarea.
         */
        "maxLength"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus.
         */
        "onInputBlur"?: (event: ModusWcTextareaCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the input value changes.
         */
        "onInputChange"?: (event: ModusWcTextareaCustomEvent<Event>) => void;
        /**
          * Emitted when the input gains focus.
         */
        "onInputFocus"?: (event: ModusWcTextareaCustomEvent<FocusEvent>) => void;
        /**
          * The placeholder text for the textarea.
         */
        "placeholder"?: string;
        /**
          * The readonly state of the textarea.
         */
        "readonly"?: boolean;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The number of visible text lines for the textarea.
         */
        "rows"?: number;
        /**
          * The size of the input.
         */
        "size"?: Size;
        /**
          * The value of the textarea.
         */
        "value"?: string;
    }
    interface ModusWcThemeProvider {
        "initialTheme"?: Partial<IThemeConfig>;
    }
    /**
     * A theme switcher component used to toggle the application theme and/or mode.
     * Allows consumers to set the initial theme (Modus Classic, Prism, etc) and end-users to toggle modes (Light, Dark).
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcThemeSwitcher {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the theme switcher element.
         */
        "customClass"?: string;
        /**
          * An event that fires when the theme is changed.
         */
        "onThemeChange"?: (event: ModusWcThemeSwitcherCustomEvent<IThemeConfig>) => void;
    }
    /**
     * A customizable checkbox component.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcToggle {
        /**
          * The ID of the element that describes the toggle.
         */
        "ariaDescribedby"?: string;
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * The aria-labelledby attribute for usage with a label.
         */
        "ariaLabelledby"?: string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass"?: string;
        /**
          * The disabled state of the toggle.
         */
        "disabled"?: boolean;
        /**
          * The indeterminate state of the toggle.
         */
        "indeterminate"?: boolean;
        /**
          * Specifies the text direction of the input content.
         */
        "inputDir"?: '' | 'ltr' | 'rtl' | 'auto';
        /**
          * The ID of the input element.
         */
        "inputId"?: string;
        /**
          * The tabindex of the input.
         */
        "inputTabIndex"?: number;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair.
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus.
         */
        "onInputBlur"?: (event: ModusWcToggleCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the input value changes.
         */
        "onInputChange"?: (event: ModusWcToggleCustomEvent<Event>) => void;
        /**
          * Emitted when the input gains focus.
         */
        "onInputFocus"?: (event: ModusWcToggleCustomEvent<FocusEvent>) => void;
        /**
          * A value is required for the form to be submittable.
         */
        "required"?: boolean;
        /**
          * The size of the input.
         */
        "size"?: Size;
        /**
          * The value of the toggle.
         */
        "value"?: boolean;
    }
    /**
     * A customizable tooltip component used to create tooltips with different content.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTooltip {
        /**
          * The text content of the tooltip.
         */
        "content"?: string;
        /**
          * Custom CSS class to apply to the inner div.
         */
        "customClass"?: string;
        /**
          * Use this attribute to force the tooltip to remain open.
         */
        "forceOpen"?: boolean;
        /**
          * The position that the tooltip will render in relation to the element.
         */
        "position"?: 'auto' | 'top' | 'right' | 'bottom' | 'left';
        /**
          * The ID of the tooltip element, useful for setting the "aria-describedby" attribute of related elements.
         */
        "tooltipId"?: string;
    }
    /**
     * A customizable typography component used to render text with different sizes, variants, and weights.
     * Adheres to WCAG 2.2 standards.
     */
    interface ModusWcTypography {
        /**
          * The aria-label attribute for accessibility.
         */
        "ariaLabel": string;
        /**
          * Custom CSS class to apply to the typography element.
         */
        "customClass"?: string;
        /**
          * The size of the font.
         */
        "size"?: Size;
        /**
          * The variant of the typography component.
         */
        "variant"?: TypographyVariant;
        /**
          * The weight of the text.
         */
        "weight"?: TypographyWeight;
    }
    interface IntrinsicElements {
        "modus-wc-avatar": ModusWcAvatar;
        "modus-wc-badge": ModusWcBadge;
        "modus-wc-button": ModusWcButton;
        "modus-wc-checkbox": ModusWcCheckbox;
        "modus-wc-date": ModusWcDate;
        "modus-wc-divider": ModusWcDivider;
        "modus-wc-icon": ModusWcIcon;
        "modus-wc-input-label": ModusWcInputLabel;
        "modus-wc-number-input": ModusWcNumberInput;
        "modus-wc-radio": ModusWcRadio;
        "modus-wc-skeleton": ModusWcSkeleton;
        "modus-wc-slider": ModusWcSlider;
        "modus-wc-spinner": ModusWcSpinner;
        "modus-wc-text-input": ModusWcTextInput;
        "modus-wc-textarea": ModusWcTextarea;
        "modus-wc-theme-provider": ModusWcThemeProvider;
        "modus-wc-theme-switcher": ModusWcThemeSwitcher;
        "modus-wc-toggle": ModusWcToggle;
        "modus-wc-tooltip": ModusWcTooltip;
        "modus-wc-typography": ModusWcTypography;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A customizable avatar component used to create avatars with different images.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-avatar": LocalJSX.ModusWcAvatar & JSXBase.HTMLAttributes<HTMLModusWcAvatarElement>;
            /**
             * A customizable badge component used to create badges with different sizes, types, and colors.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-badge": LocalJSX.ModusWcBadge & JSXBase.HTMLAttributes<HTMLModusWcBadgeElement>;
            /**
             * A customizable button component used to create buttons with different sizes, variants, and types.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-button": LocalJSX.ModusWcButton & JSXBase.HTMLAttributes<HTMLModusWcButtonElement>;
            /**
             * A customizable checkbox component.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-checkbox": LocalJSX.ModusWcCheckbox & JSXBase.HTMLAttributes<HTMLModusWcCheckboxElement>;
            /**
             * A customizable date picker component used to create date inputs.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-date": LocalJSX.ModusWcDate & JSXBase.HTMLAttributes<HTMLModusWcDateElement>;
            /**
             * A customizable divider component used to separate content horizontally or vertically.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-divider": LocalJSX.ModusWcDivider & JSXBase.HTMLAttributes<HTMLModusWcDividerElement>;
            /**
             * A customizable icon component used to render Modus icons.
             * <b>This component requires Modus icons to be installed in the host application. See [Modus Icon Usage](/docs/documentation-modus-icon-usage--docs) for steps.</b>
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-icon": LocalJSX.ModusWcIcon & JSXBase.HTMLAttributes<HTMLModusWcIconElement>;
            /**
             * A customizable input label component.
             * The component supports a `<slot>` for injecting additional custom content inside the label, such as icons or formatted text.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-input-label": LocalJSX.ModusWcInputLabel & JSXBase.HTMLAttributes<HTMLModusWcInputLabelElement>;
            /**
             * A customizable input component used to create number inputs with types.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-number-input": LocalJSX.ModusWcNumberInput & JSXBase.HTMLAttributes<HTMLModusWcNumberInputElement>;
            /**
             * A customizable radio component.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-radio": LocalJSX.ModusWcRadio & JSXBase.HTMLAttributes<HTMLModusWcRadioElement>;
            /**
             * A customizable skeleton component used to create skeletons of various sizes and shapes.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-skeleton": LocalJSX.ModusWcSkeleton & JSXBase.HTMLAttributes<HTMLModusWcSkeletonElement>;
            /**
             * A customizable slider component.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-slider": LocalJSX.ModusWcSlider & JSXBase.HTMLAttributes<HTMLModusWcSliderElement>;
            /**
             * A customizable spinner component used to indicate the loading of content.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-spinner": LocalJSX.ModusWcSpinner & JSXBase.HTMLAttributes<HTMLModusWcSpinnerElement>;
            /**
             * A customizable input component used to create text inputs with types.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-text-input": LocalJSX.ModusWcTextInput & JSXBase.HTMLAttributes<HTMLModusWcTextInputElement>;
            /**
             * A customizable textarea component.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-textarea": LocalJSX.ModusWcTextarea & JSXBase.HTMLAttributes<HTMLModusWcTextareaElement>;
            "modus-wc-theme-provider": LocalJSX.ModusWcThemeProvider & JSXBase.HTMLAttributes<HTMLModusWcThemeProviderElement>;
            /**
             * A theme switcher component used to toggle the application theme and/or mode.
             * Allows consumers to set the initial theme (Modus Classic, Prism, etc) and end-users to toggle modes (Light, Dark).
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-theme-switcher": LocalJSX.ModusWcThemeSwitcher & JSXBase.HTMLAttributes<HTMLModusWcThemeSwitcherElement>;
            /**
             * A customizable checkbox component.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-toggle": LocalJSX.ModusWcToggle & JSXBase.HTMLAttributes<HTMLModusWcToggleElement>;
            /**
             * A customizable tooltip component used to create tooltips with different content.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-tooltip": LocalJSX.ModusWcTooltip & JSXBase.HTMLAttributes<HTMLModusWcTooltipElement>;
            /**
             * A customizable typography component used to render text with different sizes, variants, and weights.
             * Adheres to WCAG 2.2 standards.
             */
            "modus-wc-typography": LocalJSX.ModusWcTypography & JSXBase.HTMLAttributes<HTMLModusWcTypographyElement>;
        }
    }
}
