// 'use client';
//
// /**
//  * This file was automatically generated by the Stencil React Output Target.
//  * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//  */
//
// /* eslint-disable */
//
// import type {
//   EventName,
//   StencilReactComponent,
// } from '@stencil/react-output-target/runtime';
// import { createComponent } from '@stencil/react-output-target/runtime';
// import {
//   type ModusWcButtonCustomEvent,
//   type ModusWcInputCustomEvent,
// } from '@trimble-cms/modus-wc';
// import {
//   ModusWcButton as ModusWcButtonElement,
//   defineCustomElement as defineModusWcButton,
// } from '@trimble-cms/modus-wc/./dist/components/modus-wc-button.js';
// import {
//   ModusWcInput as ModusWcInputElement,
//   defineCustomElement as defineModusWcInput,
// } from '@trimble-cms/modus-wc/./dist/components/modus-wc-input.js';
// import React from 'react';
//
// type ModusWcButtonEvents = {
//   onClick: EventName<ModusWcButtonCustomEvent<MouseEvent | KeyboardEvent>>;
// };
//
// export const ModusWcButton: StencilReactComponent<
//   ModusWcButtonElement,
//   ModusWcButtonEvents
// > = /*@__PURE__*/ createComponent<ModusWcButtonElement, ModusWcButtonEvents>({
//   tagName: 'modus-wc-button',
//   elementClass: ModusWcButtonElement,
//   react: React,
//   events: { onClick: 'click' } as ModusWcButtonEvents,
//   defineCustomElement: defineModusWcButton,
// });
//
// type ModusWcInputEvents = {
//   onBlur: EventName<ModusWcInputCustomEvent<FocusEvent>>;
//   onChange: EventName<CustomEvent<string>>;
//   onFocus: EventName<ModusWcInputCustomEvent<FocusEvent>>;
// };
//
// export const ModusWcInput: StencilReactComponent<
//   ModusWcInputElement,
//   ModusWcInputEvents
// > = /*@__PURE__*/ createComponent<ModusWcInputElement, ModusWcInputEvents>({
//   tagName: 'modus-wc-input',
//   elementClass: ModusWcInputElement,
//   react: React,
//   events: {
//     onBlur: 'blur',
//     onChange: 'change',
//     onFocus: 'focus',
//   } as ModusWcInputEvents,
//   defineCustomElement: defineModusWcInput,
// });
