name: Build React Integration

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build-react:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        react-version: [17, 18, 19]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      # - uses: google/wireit@setup-github-actions-caching/v2

      - name: Install dependencies
        run: npm ci

      - name: Build Stencil components
        run: npm run build:ci

      - name: Pack modus-webcomponents
        id: npm_pack
        working-directory: dist
        run: |
          modus_wc_tarball=$(npm pack --pack-destination ../integrations/react/v${{ matrix.react-version }} | tail -n 1)
          echo "modus_wc_tarball=${modus_wc_tarball}" >> $GITHUB_OUTPUT

      - name: Install dependencies for react build
        run: npm ci
        working-directory: integrations/react/v${{ matrix.react-version }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install current modus-webcomponents implementation for react integration
        run: npm install ./${{ steps.npm_pack.outputs.modus_wc_tarball }}
        working-directory: integrations/react/v${{ matrix.react-version }}

      - name: Build react integration
        id: react
        run: npm run build
        working-directory: integrations/react/v${{ matrix.react-version }}

      - name: Pack modus-webcomponents-react
        id: npm_pack_react
        working-directory: integrations/react/v${{ matrix.react-version }}/dist
        run: |
          modus_wc_react_tarball=$(npm pack --pack-destination ../test-react-v${{ matrix.react-version }} | tail -n 1)
          echo "modus_wc_react_tarball=${modus_wc_react_tarball}" >> $GITHUB_OUTPUT

      - name: Install Dependencies for Test React App
        run: npm ci
        working-directory: integrations/react/test-react-v${{ matrix.react-version }}

      - name: Install current modus-webcomponents-react implementation for react integration
        run: npm install ./${{ steps.npm_pack_react.outputs.modus_wc_react_tarball }}
        working-directory: integrations/react/test-react-v${{ matrix.react-version }}

      - name: Build Test React App
        run: npm run build
        working-directory: integrations/react/test-react-v${{ matrix.react-version }}
