name: Build Angular Integration

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build-angular:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        angular-version: [20, 21]
        include:
          # Angular 20+ requires Node.js >=20.19 or >=22.12
          - angular-version: 20
            node-version: '22.12'
          - angular-version: 21
            node-version: '22.12'

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version || vars.NODE_VERSION }}
          cache: 'npm'

      # - uses: google/wireit@setup-github-actions-caching/v2

      - name: Install dependencies
        run: npm ci

      - name: Build Stencil components
        run: npm run build:ci

      - name: Pack modus-wc
        id: npm_pack
        working-directory: dist
        run: |
          modus_wc_tarball=$(npm pack --pack-destination ../integrations/angular/ng${{ matrix.angular-version }} | tail -n 1)
          echo "modus_wc_tarball=${modus_wc_tarball}" >> $GITHUB_OUTPUT

      - name: Install dependencies for angular build
        run: npm ci
        working-directory: integrations/angular/ng${{ matrix.angular-version }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install current modus-wc implementation for angular integration
        run: npm install ./${{ steps.npm_pack.outputs.modus_wc_tarball }}
        working-directory: integrations/angular/ng${{ matrix.angular-version }}

      - name: Build angular integration
        run: npm run build
        working-directory: integrations/angular/ng${{ matrix.angular-version }}
