name: Build React Integration

on: workflow_call

jobs:
  build-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build Stencil components
        id: stencil
        run: npm run stencil:build
        continue-on-error: true

      - name: Pack modus-wc
        id: npm_pack
        run: |
          modus_wc_tarball=$(npm pack --pack-destination integrations/react | tail -n 1)
          echo "modus_wc_tarball=${modus_wc_tarball}" >> $GITHUB_OUTPUT
        continue-on-error: false

      - name: Install dependencies for react build
        run: npm ci
        working-directory: integrations/react
        continue-on-error: false
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install current modus-wc implementation for react integration
        run: npm install ./${{ steps.npm_pack.outputs.modus_wc_tarball }}
        working-directory: integrations/react
        continue-on-error: false

      - name: Build react integration
        id: react
        run: npm run build
        working-directory: integrations/react
        continue-on-error: true