name: Build Vue Integration

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build-vue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      # - uses: google/wireit@setup-github-actions-caching/v2

      - name: Install dependencies
        run: npm ci

      - name: Build Stencil components
        run: npm run build:ci

      - name: Pack modus-webcomponents
        id: npm_pack
        working-directory: dist
        run: |
          modus_wc_tarball=$(npm pack --pack-destination ../integrations/vue/v-latest | tail -n 1)
          echo "modus_wc_tarball=${modus_wc_tarball}" >> $GITHUB_OUTPUT

      - name: Install dependencies for vue build
        run: npm ci
        working-directory: integrations/vue/v-latest
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install current modus-webcomponents implementation for vue integration
        run: npm install ./${{ steps.npm_pack.outputs.modus_wc_tarball }}
        working-directory: integrations/vue/v-latest

      - name: Build vue integration
        id: vue
        run: npm run build
        working-directory: integrations/vue/v-latest

      - name: Pack modus-webcomponents-vue
        id: npm_pack_vue
        working-directory: integrations/vue/v-latest/dist
        run: |
          modus_wc_vue_tarball=$(npm pack --pack-destination ../../test-app | tail -n 1)
          echo "modus_wc_vue_tarball=${modus_wc_vue_tarball}" >> $GITHUB_OUTPUT

      - name: Copy modus-webcomponents tarball to test app directory (relative resolution)
        run: cp integrations/vue/v-latest/${{ steps.npm_pack.outputs.modus_wc_tarball }} integrations/vue/test-app/

      - name: Install Dependencies for Test Vue App
        run: npm ci
        working-directory: integrations/vue/test-app

      - name: Install current modus-webcomponents-vue implementation for vue integration
        run: npm install ./${{ steps.npm_pack_vue.outputs.modus_wc_vue_tarball }}
        working-directory: integrations/vue/test-app

      - name: Build Test Vue App
        run: npm run build
        working-directory: integrations/vue/test-app
