name: Merge Gate

on:
  pull_request:
    branches: [main]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        id: lint
        run: npm run lint
        continue-on-error: true

      - name: Run Prettier
        id: prettier
        run: npm run code-style
        continue-on-error: true

      - name: Build Stencil components
        id: stencil
        run: npm run stencil:build
        continue-on-error: true

      - name: Build Storybook project
        id: storybook
        run: npm run storybook:build
        continue-on-error: true

      - name: Run unit tests and check code coverage
        id: tests
        run: npm run test:coverage
        continue-on-error: true

      - name: Check for step failures
        if: always()
        run: |
          if [ "${{ steps.lint.outcome }}" == "failure" ] || \
             [ "${{ steps.prettier.outcome }}" == "failure" ] || \
             [ "${{ steps.stencil.outcome }}" == "failure" ] || \
             [ "${{ steps.storybook.outcome }}" == "failure" ] || \
             [ "${{ steps.tests.outcome }}" == "failure" ]; then
            echo "One or more steps have failed. Please review the logs and fix the issues before merging."
            exit 1
          fi

  build-react-integration:
    uses: ./.github/workflows/build-react.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
