# This publishes various packages in this repository.
# It will update the package.json version, build the react package, publish it to the Artifactory NPM registry, as well as create a GitHub release.
# This is triggered by running the main 'Publish & Release' workflow.

name: Publish & Release - React

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string

permissions:
  contents: write
  actions: write

jobs:
  build-and-publish-react:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-version: [17, 18]

    defaults:
      run:
        working-directory: integrations/react/v${{ matrix.react-version }}

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      # - uses: google/wireit@setup-github-actions-caching/v2

      - name: Install Web Component dependencies
        run: npm ci
        working-directory: .
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            integrations/react/v${{ matrix.react-version }}/package-lock.json

      - name: Build Web Components
        run: npm run build:ci
        working-directory: .

      - name: Update to use new WebComponent version
        run: |
          jq --arg version "${{ github.event.inputs.version }}" \
          '.dependencies["@trimble-cms/modus-wc"] = $version' package.json > package.json.tmp && \
          mv package.json.tmp package.json && npm i

      - name: Update package.json version
        run: |
          jq --arg version "${{ github.event.inputs.version }}-react${{ matrix.react-version }}" \
          '.version = $version' package.json > package.json.tmp && \
          mv package.json.tmp package.json

      - name: Build distribution
        run: npm run build

      - name: Package distribution
        run: npm pack

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-${{ matrix.react-version }}-distribution-v${{ github.event.inputs.version }}-react${{ matrix.react-version }}
          path: '**/*.tgz'

      - name: Publish distribution
        run: npm publish

  release-react:
    needs: build-and-publish-react
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-version: [17, 18]

    defaults:
      run:
        working-directory: integrations/react/v${{ matrix.react-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-${{ matrix.react-version }}-distribution-v${{ github.event.inputs.version }}-react${{ matrix.react-version }}
          path: .

      - name: Find the release asset
        id: find-asset
        run: |
          asset_path=$(find . -name 'trimble-cms-modus-wc-react*.tgz')
          full_asset_path="${{ github.workspace }}/integrations/react/v${{ matrix.react-version }}/${asset_path}"
          echo "asset_path=$full_asset_path" >> $GITHUB_OUTPUT

      - name: Rename release asset
        run: mv ${{ steps.find-asset.outputs.asset_path }} package-react${{ matrix.react-version }}.tgz

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: modus-wc-react-${{ github.event.inputs.version }}-react${{ matrix.react-version }}
          name: Modus Web Components React ${{ github.event.inputs.version }} (React ${{ matrix.react-version }})
          files: |
            **/package-react${{ matrix.react-version }}.tgz
