name: Publish React Integration

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci --prefix integrations/react
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update package.json version
        run: jq --arg version "${{ github.event.inputs.version }}" '.version = $version' integrations/react/package.json > integrations/react/package.json.tmp && mv integrations/react/package.json.tmp integrations/react/package.json

      - name: Build React integration
        run: npm run build --prefix integrations/react

      - name: Configure npm registry
        run: npm config set registry https://artifactory.trimble.tools/artifactory/api/npm/trimble-cms-trimble-accounting-npm/

      - name: Authenticate to Artifactory
        run: echo "//artifactory.trimble.tools/artifactory/api/npm/trimble-cms-trimble-accounting-npm/:_authToken=${ARTIFACTORY_TOKEN}" >> .npmrc
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Pack the package
        run: |
          cd integrations/react
          npm pack
        id: npm_pack

      - name: Upload tarball as artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-tarball
          path: './integrations/react/*.tgz'

      - name: Publish
        run: |
          cd integrations/react
          npm publish
        continue-on-error: true

  release:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist directory
        uses: actions/download-artifact@v4
        with:
          name: npm-tarball
          path: ./integrations/react

      - name: Create GitHub release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: modus-wc-react-${{ github.event.inputs.version }}
          name: Modus Web Components React ${{ github.event.inputs.version }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./integrations/react/trimble-cms-modus-wc-react-*.tgz
          asset_name: package.tgz
          asset_content_type: application/gzip
