# This publishes various packages in this repository.
# It will update the package.json version, build the Angular package, publish it to the Artifactory NPM registry, as well as create a GitHub release.
# This is triggered by running the main 'Publish & Release' workflow.

name: Publish & Release - Angular

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string

permissions:
  contents: write
  actions: write

jobs:
  build-and-publish-angular:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: integrations/angular/ng18

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      - uses: google/wireit@setup-github-actions-caching/v2

      - name: Install Web Component dependencies
        run: npm ci
        working-directory: .

      - name: Build Web Components
        run: npm run build:ci
        working-directory: .

      - name: Update to use new WebComponent version
        run: |
          jq --arg version "${{ github.event.inputs.version }}" \
          '.dependencies["@trimble-cms/modus-wc"] = $version' package.json > package.json.tmp && \
          mv package.json.tmp package.json && npm i && \
          cd projects/trimble-cms/modus-wc-ng && \
          jq --arg version "${{ github.event.inputs.version }}" \
          '.peerDependencies["@trimble-cms/modus-wc"] = $version' package.json > package.json.tmp && \
          mv package.json.tmp package.json && npm i

      - name: Update package.json version
        run: |
          cd projects/trimble-cms/modus-wc-ng && \
          jq --arg version "${{ github.event.inputs.version }}-ng18" \
          '.version = $version' package.json > package.json.tmp && \
          mv package.json.tmp package.json

      - name: Build distribution
        run: npm run build

      - name: Package distribution
        run: npm pack ./dist/trimble-cms/modus-wc-ng

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-distribution
          path: '**/*.tgz'

      - name: Publish distribution
        run: npm publish *.tgz

  release-angular:
    needs: build-and-publish-angular
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: integrations/angular/ng18

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download tarball artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-distribution
          path: .

      - name: Find the release asset
        id: find-asset
        run: |
          asset_path=$(find . -name 'trimble-cms-modus-wc-ng*.tgz')
          full_asset_path="${{ github.workspace }}/integrations/angular/ng18/${asset_path}"
          echo "asset_path=$full_asset_path" >> $GITHUB_OUTPUT

      - name: Rename release asset
        run: mv ${{ steps.find-asset.outputs.asset_path }} package-angular-18.tgz

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: modus-wc-ng-${{ github.event.inputs.version }}-ng18
          name: Modus Web Components Angular ${{ github.event.inputs.version }}-ng18
          files: package-angular-18.tgz
