# This publishes various packages in this repository.
# It will update the package.json version, build the packages, publish them to the Artifactory NPM registry, as well as create a GitHub release.
# The packages consist of:
# - The Web Components package
# - The React package
# - The Angular package
# This is triggered by a manual run with a specified version number.

name: Publish & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string

permissions:
  contents: write
  actions: write

jobs:
  build-and-publish-wc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      - uses: google/wireit@setup-github-actions-caching/v2

      - name: Install dependencies
        run: npm ci

      - name: Update package.json version
        run: |
          jq --arg version "${{ github.event.inputs.version }}" \
          '.version = $version' package.json > package.json.tmp && \
          mv package.json.tmp package.json

      - name: Build web components
        run: npm run build:ci

      - name: Configure npm registry
        run: npm config set registry https://artifactory.trimble.tools/artifactory/api/npm/trimble-cms-trimble-accounting-npm/

      - name: Authenticate to Artifactory
        run: echo "//artifactory.trimble.tools/artifactory/api/npm/trimble-cms-trimble-accounting-npm/:_authToken=${ARTIFACTORY_TOKEN}" >> .npmrc
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Pack the package
        run: npm pack
        id: npm_pack

      - name: Upload tarball as artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-tarball
          path: '*.tgz'

      - name: Publish
        run: npm publish
        continue-on-error: false

  trigger-angular-publish:
    needs: build-and-publish-wc
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Angular Publish Workflow
        uses: benc-uk/workflow-dispatch@v1.2
        with:
          workflow: publish-angular.yml
          inputs: '{"version": "${{ github.event.inputs.version }}"}'

  trigger-react-publish:
    needs: build-and-publish-wc
    runs-on: ubuntu-latest
    steps:
      - name: Trigger React Publish Workflow
        uses: benc-uk/workflow-dispatch@v1.2
        with:
          workflow: publish-react.yml
          inputs: '{"version": "${{ github.event.inputs.version }}"}'

  release-wc:
    needs: build-and-publish-wc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download tarball artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-tarball
          path: .

      - name: Find the asset
        id: find-asset
        run: echo "asset_path=$(find . -name 'trimble-cms-modus-wc-*.tgz')" >> $GITHUB_OUTPUT

      - name: Rename the asset to package.tgz
        run: mv ${{ steps.find-asset.outputs.asset_path }} package.tgz

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: modus-wc-${{ github.event.inputs.version }}
          name: Modus Web Components ${{ github.event.inputs.version }}
          files: |
            package.tgz
