name: Publish React Integration

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci --prefix integrations/react

      - name: Build React integration
        run: npm run build --prefix integrations/react

      - name: Copy package.json to dist
        run: cp integrations/react/package.json dist/

      - name: Update package.json version
        run: jq --arg version "${{ github.event.inputs.version }}" '.version = $version' integrations/react/dist/package.json > integrations/react/dist/package.json.tmp && mv integrations/react/dist/package.json.tmp integrations/react/dist/package.json

      - name: Upload dist directory
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: integrations/react/dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist directory
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: integrations/react/dist

      - name: Configure npm registry
        run: npm config set registry https://artifactory.trimble.tools/artifactory/api/npm/trimble-cms-trimble-accounting-npm/

      - name: Authenticate to Artifactory
        run: echo "//artifactory.trimble.tools/artifactory/api/npm/trimble-cms-trimble-accounting-npm/:_authToken=${ARTIFACTORY_TOKEN}" >> .npmrc
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create .npmrc in dist
        run: |
          echo "//artifactory.trimble.tools/artifactory/api/npm/trimble-cms-trimble-accounting-npm/:_authToken=${ARTIFACTORY_TOKEN}" > integrations/react/dist/.npmrc
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: |
          cd integrations/react/dist
          npm publish
        continue-on-error: true

  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist directory
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: integrations/react/dist

      - name: Zip dist directory
        run: zip -r dist.zip integrations/react/dist/

      - name: Create GitHub release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          name: modus-wc-react-${{ github.event.inputs.version }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
