name: Publish Web Components

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Update package.json version
        run: jq --arg version "${{ github.event.inputs.version }}" '.version = $version' package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Build web components
        run: npm run stencil:build

      - name: Configure npm registry
        run: npm config set registry https://artifactory.trimble.tools/artifactory/api/npm/trimble-cms-trimble-accounting-npm/

      - name: Authenticate to Artifactory
        run: echo "//artifactory.trimble.tools/artifactory/api/npm/trimble-cms-trimble-accounting-npm/:_authToken=${ARTIFACTORY_TOKEN}" >> .npmrc
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Pack the package
        run: npm pack
        id: npm_pack

      - name: Upload tarball as artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-tarball
          path: '*.tgz'

      - name: Publish
        run: npm publish
        continue-on-error: true

  release:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: list files 1
        run: ls -la

      - name: Download tarball artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-tarball
          path: .

      # List files in the current directory
      - name: list files 2
        run: ls -la

      - name: Find the asset
        id: find-asset
        run: echo "::set-output name=asset_path::$(find . -name 'trimble-cms-modus-wc-*.tgz')"

      - name: Create GitHub release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: modus-wc-${{ github.event.inputs.version }}
          name: Modus Web Components ${{ github.event.inputs.version }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.tgz
          asset_name: package.tgz
          asset_content_type: application/gzip
